const C = (ts) => [{ timestamp: ts, user: "Admin", action: "Created", changes: "Record created" }];
const D = "2024-01-05T09:00:00.000Z";
const A = "2024-01-15T09:00:00.000Z";

// ─── Work Order Types ─────────────────────────────────────────
export const SEED_WORK_ORDER_TYPES = [
  { id: "wot001", typeId: "WOT-00001", typeName: "Manufacturing Order",          description: "Standard production run for finished goods",          requiresApproval: false, isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "wot002", typeId: "WOT-00002", typeName: "Repair Order",                 description: "Asset or equipment breakdown repair",                 requiresApproval: true,  isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "wot003", typeId: "WOT-00003", typeName: "Job Work Order",               description: "Outsourced machining or fabrication operations",       requiresApproval: true,  isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "wot004", typeId: "WOT-00004", typeName: "Preventive Maintenance Order", description: "Scheduled PM activities per maintenance calendar",     requiresApproval: false, isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "wot005", typeId: "WOT-00005", typeName: "Rework Order",                 description: "Correction of defective or non-conforming products",  requiresApproval: false, isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
];

// ─── Unit Types ───────────────────────────────────────────────
export const SEED_UNIT_TYPES = [
  { id: "ut001", unitTypeId: "UT-00001", unitTypeName: "Weight",      isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "ut002", unitTypeId: "UT-00002", unitTypeName: "Length",      isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "ut003", unitTypeId: "UT-00003", unitTypeName: "Volume",      isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "ut004", unitTypeId: "UT-00004", unitTypeName: "Count / Nos", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "ut005", unitTypeId: "UT-00005", unitTypeName: "Time",        isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "ut006", unitTypeId: "UT-00006", unitTypeName: "Area",        isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
];

// ─── Units of Measure ─────────────────────────────────────────
export const SEED_UOM = [
  { id: "uom001", unitId: "UOM-00001", unitTypeId: "ut001", unitTypeName: "Weight",      unitName: "Kilogram",   unitShortCode: "KGS", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "uom002", unitId: "UOM-00002", unitTypeId: "ut001", unitTypeName: "Weight",      unitName: "Gram",       unitShortCode: "GRM", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "uom003", unitId: "UOM-00003", unitTypeId: "ut001", unitTypeName: "Weight",      unitName: "Metric Ton", unitShortCode: "TON", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "uom004", unitId: "UOM-00004", unitTypeId: "ut002", unitTypeName: "Length",      unitName: "Metre",      unitShortCode: "MTR", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "uom005", unitId: "UOM-00005", unitTypeId: "ut002", unitTypeName: "Length",      unitName: "Millimetre", unitShortCode: "MM",  isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "uom006", unitId: "UOM-00006", unitTypeId: "ut002", unitTypeName: "Length",      unitName: "Feet",       unitShortCode: "FT",  isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "uom007", unitId: "UOM-00007", unitTypeId: "ut003", unitTypeName: "Volume",      unitName: "Litre",      unitShortCode: "LTR", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "uom008", unitId: "UOM-00008", unitTypeId: "ut003", unitTypeName: "Volume",      unitName: "Millilitre", unitShortCode: "ML",  isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "uom009", unitId: "UOM-00009", unitTypeId: "ut004", unitTypeName: "Count / Nos", unitName: "Numbers",    unitShortCode: "NOS", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "uom010", unitId: "UOM-00010", unitTypeId: "ut004", unitTypeName: "Count / Nos", unitName: "Set",        unitShortCode: "SET", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "uom011", unitId: "UOM-00011", unitTypeId: "ut004", unitTypeName: "Count / Nos", unitName: "Packet",     unitShortCode: "PKT", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "uom012", unitId: "UOM-00012", unitTypeId: "ut005", unitTypeName: "Time",        unitName: "Hour",       unitShortCode: "HRS", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
];

// ─── Asset Structures (Locations) ─────────────────────────────
const L = "2024-01-10T09:00:00.000Z";
export const SEED_ASSET_STRUCTURES = [
  { id: "loc001", locationId: "LOC-001", locationName: "Production Floor Block A", site: "Main Plant",    warehouseId: "wh001", warehouseName: "Main Warehouse", createdAt: L, updatedAt: L, createdBy: "Admin", updatedBy: "Admin", changelog: C(L) },
  { id: "loc002", locationId: "LOC-002", locationName: "Assembly Bay",             site: "Main Plant",    warehouseId: "wh001", warehouseName: "Main Warehouse", createdAt: L, updatedAt: L, createdBy: "Admin", updatedBy: "Admin", changelog: C(L) },
  { id: "loc003", locationId: "LOC-003", locationName: "Compressor House",         site: "Utility Block", warehouseId: "",      warehouseName: "",               createdAt: L, updatedAt: L, createdBy: "Admin", updatedBy: "Admin", changelog: C(L) },
  { id: "loc004", locationId: "LOC-004", locationName: "Utility & Services Room",  site: "Utility Block", warehouseId: "",      warehouseName: "",               createdAt: L, updatedAt: L, createdBy: "Admin", updatedBy: "Admin", changelog: C(L) },
  { id: "loc005", locationId: "LOC-005", locationName: "Warehouse & Dispatch Bay", site: "Main Plant",    warehouseId: "wh001", warehouseName: "Main Warehouse", createdAt: L, updatedAt: L, createdBy: "Admin", updatedBy: "Admin", changelog: C(L) },
];

// ─── Assets ───────────────────────────────────────────────────
export const SEED_ASSETS = [
  { id: "ast001", assetId: "AST-001", name: "CNC Machining Centre",   locationId: "loc001", locationName: "Production Floor Block A", assetTypeId: "", assetTypeName: "Machinery",         manufacturer: "BFW India",     modelNo: "BFW-CNC-VF4", serialNo: "BFW2021031401", installationDate: "2021-03-14", warrantyDetails: "5 years expires Mar 2026", level: "1", status: "Active",           consumedHours: "4820",  createdAt: A, updatedAt: A, createdBy: "Admin", updatedBy: "Admin", changelog: C(A) },
  { id: "ast002", assetId: "AST-002", name: "Air Compressor 150 CFM", locationId: "loc003", locationName: "Compressor House",         assetTypeId: "", assetTypeName: "Compressed Air",    manufacturer: "Atlas Copco",   modelNo: "GA37VSD",     serialNo: "AC20190827A3",  installationDate: "2019-08-27", warrantyDetails: "3 years expired Aug 2022",  level: "1", status: "Active",           consumedHours: "12453", createdAt: A, updatedAt: A, createdBy: "Admin", updatedBy: "Admin", changelog: C(A) },
  { id: "ast003", assetId: "AST-003", name: "DG Set 250 kVA",         locationId: "loc004", locationName: "Utility & Services Room",  assetTypeId: "", assetTypeName: "Electrical",        manufacturer: "Cummins India", modelNo: "C250D5",      serialNo: "CUM220503B1",   installationDate: "2022-05-03", warrantyDetails: "2 years expired May 2024",  level: "1", status: "Active",           consumedHours: "3204",  createdAt: A, updatedAt: A, createdBy: "Admin", updatedBy: "Admin", changelog: C(A) },
  { id: "ast004", assetId: "AST-004", name: "Conveyor Belt System",   locationId: "loc002", locationName: "Assembly Bay",             assetTypeId: "", assetTypeName: "Material Handling", manufacturer: "FlexLink",      modelNo: "XK-45",       serialNo: "FL2020110401",  installationDate: "2020-11-04", warrantyDetails: "2 years expired Nov 2022",  level: "1", status: "Active",           consumedHours: "18600", createdAt: A, updatedAt: A, createdBy: "Admin", updatedBy: "Admin", changelog: C(A) },
  { id: "ast005", assetId: "AST-005", name: "Hydraulic Press 100T",   locationId: "loc001", locationName: "Production Floor Block A", assetTypeId: "", assetTypeName: "Machinery",         manufacturer: "Hydropack",     modelNo: "HP-100T",     serialNo: "HP2018060201",  installationDate: "2018-06-02", warrantyDetails: "3 years expired Jun 2021",  level: "1", status: "Under Maintenance", consumedHours: "22309", createdAt: A, updatedAt: A, createdBy: "Admin", updatedBy: "Admin", changelog: C(A) },
  { id: "ast006", assetId: "AST-006", name: "EOT Overhead Crane 5T",  locationId: "loc002", locationName: "Assembly Bay",             assetTypeId: "", assetTypeName: "Material Handling", manufacturer: "Indef",         modelNo: "EOT-5T-A",    serialNo: "INDEF230704C2", installationDate: "2023-07-04", warrantyDetails: "2 years expires Jul 2025",  level: "1", status: "Active",           consumedHours: "1870",  createdAt: A, updatedAt: A, createdBy: "Admin", updatedBy: "Admin", changelog: C(A) },
];

// ─── Maintenance Types ────────────────────────────────────────
const M = "2024-01-08T09:00:00.000Z";
export const SEED_MAINTENANCE_TYPES = [
  { id: "mt001", typeId: "MT-00001", maintenanceName: "Preventive Maintenance", priority: "Medium",   duration: "4",  isDeactivated: false, createdAt: M, updatedAt: M, createdBy: "Admin", updatedBy: "Admin", changelog: C(M) },
  { id: "mt002", typeId: "MT-00002", maintenanceName: "Breakdown Maintenance",  priority: "Critical", duration: "8",  isDeactivated: false, createdAt: M, updatedAt: M, createdBy: "Admin", updatedBy: "Admin", changelog: C(M) },
  { id: "mt003", typeId: "MT-00003", maintenanceName: "Corrective Maintenance", priority: "High",     duration: "6",  isDeactivated: false, createdAt: M, updatedAt: M, createdBy: "Admin", updatedBy: "Admin", changelog: C(M) },
  { id: "mt004", typeId: "MT-00004", maintenanceName: "Predictive Maintenance", priority: "Low",      duration: "2",  isDeactivated: false, createdAt: M, updatedAt: M, createdBy: "Admin", updatedBy: "Admin", changelog: C(M) },
  { id: "mt005", typeId: "MT-00005", maintenanceName: "Overhauling",            priority: "High",     duration: "24", isDeactivated: false, createdAt: M, updatedAt: M, createdBy: "Admin", updatedBy: "Admin", changelog: C(M) },
  { id: "mt006", typeId: "MT-00006", maintenanceName: "Lubrication & Greasing", priority: "Low",      duration: "1",  isDeactivated: false, createdAt: M, updatedAt: M, createdBy: "Admin", updatedBy: "Admin", changelog: C(M) },
];

// ─── Job List ─────────────────────────────────────────────────
export const SEED_JOB_LIST = [
  { id: "job001", jobId: "JOB-000001", jobDate: "2026-06-01", assetId: "ast002", assetName: "Air Compressor 150 CFM", assetLocation: "Compressor House",         maintenanceTypeId: "mt001", maintenanceTypeName: "Preventive Maintenance", priority: "Medium",   problemDescription: "Monthly PM due check oil level clean filters inspect belts and safety valves.",                                     assignedToId: "emp003", assignedToName: "Anil Kumar",  startTime: "2026-06-01T08:00", endTime: "2026-06-01T12:00", estimatedDuration: "4",  status: "Completed",   actualDuration: "3.5", workDoneRemarks: "Oil changed, air filter cleaned, belt tension adjusted. All safety valves operational. Next PM due 01-Jul-2026.", consumedHoursUpdate: "12453", attachments: [], createdAt: "2026-06-01T07:30:00.000Z", updatedAt: "2026-06-01T12:15:00.000Z", createdBy: "Admin", updatedBy: "Anil Kumar",  changelog: C("2026-06-01T07:30:00.000Z") },
  { id: "job002", jobId: "JOB-000002", jobDate: "2026-06-05", assetId: "ast005", assetName: "Hydraulic Press 100T",   assetLocation: "Production Floor Block A", maintenanceTypeId: "mt002", maintenanceTypeName: "Breakdown Maintenance",  priority: "Critical", problemDescription: "Press not building pressure beyond 60T. Production halted. Suspected hydraulic pump failure.",                     assignedToId: "emp003", assignedToName: "Anil Kumar",  startTime: "2026-06-05T09:00", endTime: "2026-06-05T18:00", estimatedDuration: "8",  status: "Completed",   actualDuration: "9",   workDoneRemarks: "Hydraulic pump seal replaced. New seal kit installed HP-SK-100. System tested at 110T OK. Asset Under Maintenance pending QC sign-off.", consumedHoursUpdate: "22309", attachments: [], createdAt: "2026-06-05T08:45:00.000Z", updatedAt: "2026-06-05T18:10:00.000Z", createdBy: "Admin", updatedBy: "Anil Kumar",  changelog: C("2026-06-05T08:45:00.000Z") },
  { id: "job003", jobId: "JOB-000003", jobDate: "2026-06-10", assetId: "ast001", assetName: "CNC Machining Centre",   assetLocation: "Production Floor Block A", maintenanceTypeId: "mt006", maintenanceTypeName: "Lubrication & Greasing", priority: "Low",      problemDescription: "Scheduled weekly lubrication of spindle ball screws and linear guides.",                                          assignedToId: "emp004", assignedToName: "Priya Desai", startTime: "2026-06-10T07:30", endTime: "2026-06-10T08:30", estimatedDuration: "1",  status: "Completed",   actualDuration: "1",   workDoneRemarks: "Spindle oil topped up. Ball screws greased with OKS 425. All guide ways lubricated. Machine ready for production.", consumedHoursUpdate: "4821", attachments: [], createdAt: "2026-06-10T07:00:00.000Z", updatedAt: "2026-06-10T08:45:00.000Z", createdBy: "Admin", updatedBy: "Priya Desai", changelog: C("2026-06-10T07:00:00.000Z") },
  { id: "job004", jobId: "JOB-000004", jobDate: "2026-06-15", assetId: "ast003", assetName: "DG Set 250 kVA",         assetLocation: "Utility & Services Room",  maintenanceTypeId: "mt001", maintenanceTypeName: "Preventive Maintenance", priority: "Medium",   problemDescription: "Quarterly PM engine service coolant check battery test and full load test.",                                      assignedToId: "emp003", assignedToName: "Anil Kumar",  startTime: "2026-06-15T09:00", endTime: "2026-06-15T13:30", estimatedDuration: "4",  status: "Completed",   actualDuration: "4.5", workDoneRemarks: "Engine oil and filter changed. Coolant topped up. Battery terminals cleaned. Load test at 70% capacity 415V stable. Next PM due 15-Sep-2026.", consumedHoursUpdate: "3204", attachments: [], createdAt: "2026-06-15T08:30:00.000Z", updatedAt: "2026-06-15T13:45:00.000Z", createdBy: "Admin", updatedBy: "Anil Kumar",  changelog: C("2026-06-15T08:30:00.000Z") },
  { id: "job005", jobId: "JOB-000005", jobDate: "2026-06-20", assetId: "ast004", assetName: "Conveyor Belt System",   assetLocation: "Assembly Bay",             maintenanceTypeId: "mt003", maintenanceTypeName: "Corrective Maintenance",  priority: "High",     problemDescription: "Belt slipping on drive pulley section 3. Tension lost visible misalignment and abnormal noise on startup.",      assignedToId: "emp003", assignedToName: "Anil Kumar",  startTime: "2026-06-20T10:00", endTime: "",                  estimatedDuration: "6",  status: "In Progress", actualDuration: "",    workDoneRemarks: "", consumedHoursUpdate: "", attachments: [], createdAt: "2026-06-20T09:30:00.000Z", updatedAt: "2026-06-20T10:05:00.000Z", createdBy: "Admin", updatedBy: "Anil Kumar",  changelog: C("2026-06-20T09:30:00.000Z") },
  { id: "job006", jobId: "JOB-000006", jobDate: "2026-06-22", assetId: "ast006", assetName: "EOT Overhead Crane 5T",  assetLocation: "Assembly Bay",             maintenanceTypeId: "mt004", maintenanceTypeName: "Predictive Maintenance",  priority: "Low",      problemDescription: "Vibration sensor reading elevated on hoist motor. Scheduled inspection before next heavy lift operation.",       assignedToId: "emp004", assignedToName: "Priya Desai", startTime: "2026-06-22T14:00", endTime: "",                  estimatedDuration: "2",  status: "In Progress", actualDuration: "",    workDoneRemarks: "", consumedHoursUpdate: "", attachments: [], createdAt: "2026-06-22T13:30:00.000Z", updatedAt: "2026-06-22T14:10:00.000Z", createdBy: "Admin", updatedBy: "Priya Desai", changelog: C("2026-06-22T13:30:00.000Z") },
  { id: "job007", jobId: "JOB-000007", jobDate: "2026-06-25", assetId: "ast001", assetName: "CNC Machining Centre",   assetLocation: "Production Floor Block A", maintenanceTypeId: "mt003", maintenanceTypeName: "Corrective Maintenance",  priority: "High",     problemDescription: "Spindle alarm triggered Z-axis position error. Machine auto-stopped mid-cycle. Possible tool crash during last op.", assignedToId: "emp003", assignedToName: "Anil Kumar",  startTime: "2026-06-25T08:00", endTime: "",                  estimatedDuration: "6",  status: "Open",        actualDuration: "",    workDoneRemarks: "", consumedHoursUpdate: "", attachments: [], createdAt: "2026-06-25T07:45:00.000Z", updatedAt: "2026-06-25T07:45:00.000Z", createdBy: "Admin", updatedBy: "Admin",       changelog: C("2026-06-25T07:45:00.000Z") },
  { id: "job008", jobId: "JOB-000008", jobDate: "2026-06-26", assetId: "ast002", assetName: "Air Compressor 150 CFM", assetLocation: "Compressor House",         maintenanceTypeId: "mt005", maintenanceTypeName: "Overhauling",            priority: "High",     problemDescription: "Annual overhaul due at 12000+ hours. Piston rings cylinder valves and shaft seals to be replaced per OEM schedule.", assignedToId: "emp003", assignedToName: "Anil Kumar",  startTime: "2026-06-26T08:00", endTime: "",                  estimatedDuration: "24", status: "Open",        actualDuration: "",    workDoneRemarks: "", consumedHoursUpdate: "", attachments: [], createdAt: "2026-06-26T07:30:00.000Z", updatedAt: "2026-06-26T07:30:00.000Z", createdBy: "Admin", updatedBy: "Admin",       changelog: C("2026-06-26T07:30:00.000Z") },
];
