const C = ts => [{ timestamp: ts, user: "Admin", action: "Created", changes: "Record created" }];
const D = "2024-01-01T00:00:00.000Z";

// ─── Countries ───────────────────────────────────────────────
export const SEED_COUNTRIES = [
  { id: "cty001", countryCode: "IN",  countryName: "India",                dialCode: "+91",  currency: "INR", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "cty002", countryCode: "US",  countryName: "United States",        dialCode: "+1",   currency: "USD", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "cty003", countryCode: "GB",  countryName: "United Kingdom",       dialCode: "+44",  currency: "GBP", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "cty004", countryCode: "AE",  countryName: "United Arab Emirates", dialCode: "+971", currency: "AED", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "cty005", countryCode: "SG",  countryName: "Singapore",            dialCode: "+65",  currency: "SGD", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "cty006", countryCode: "DE",  countryName: "Germany",              dialCode: "+49",  currency: "EUR", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
];

// ─── States ───────────────────────────────────────────────────
export const SEED_STATES = [
  { id: "st001", stateCode: "MH",  stateName: "Maharashtra",       countryId: "cty001", countryName: "India", gstStateCode: "27", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "st002", stateCode: "GJ",  stateName: "Gujarat",           countryId: "cty001", countryName: "India", gstStateCode: "24", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "st003", stateCode: "KA",  stateName: "Karnataka",         countryId: "cty001", countryName: "India", gstStateCode: "29", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "st004", stateCode: "DL",  stateName: "Delhi",             countryId: "cty001", countryName: "India", gstStateCode: "07", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "st005", stateCode: "TN",  stateName: "Tamil Nadu",        countryId: "cty001", countryName: "India", gstStateCode: "33", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "st006", stateCode: "RJ",  stateName: "Rajasthan",         countryId: "cty001", countryName: "India", gstStateCode: "08", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "st007", stateCode: "UP",  stateName: "Uttar Pradesh",     countryId: "cty001", countryName: "India", gstStateCode: "09", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "st008", stateCode: "WB",  stateName: "West Bengal",       countryId: "cty001", countryName: "India", gstStateCode: "19", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "st009", stateCode: "MP",  stateName: "Madhya Pradesh",    countryId: "cty001", countryName: "India", gstStateCode: "23", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "st010", stateCode: "PB",  stateName: "Punjab",            countryId: "cty001", countryName: "India", gstStateCode: "03", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "st011", stateCode: "AP",  stateName: "Andhra Pradesh",    countryId: "cty001", countryName: "India", gstStateCode: "37", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "st012", stateCode: "TS",  stateName: "Telangana",         countryId: "cty001", countryName: "India", gstStateCode: "36", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "st013", stateCode: "HR",  stateName: "Haryana",           countryId: "cty001", countryName: "India", gstStateCode: "06", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "st014", stateCode: "OR",  stateName: "Odisha",            countryId: "cty001", countryName: "India", gstStateCode: "21", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "st015", stateCode: "GA",  stateName: "Goa",               countryId: "cty001", countryName: "India", gstStateCode: "30", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
];

// ─── Districts ────────────────────────────────────────────────
export const SEED_DISTRICTS = [
  { id: "dist001", districtCode: "DIST-MH-PUN", districtName: "Pune",            state: "Maharashtra",  districtHQ: "Pune City",   isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dist002", districtCode: "DIST-MH-MUM", districtName: "Mumbai",          state: "Maharashtra",  districtHQ: "Mumbai",      isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dist003", districtCode: "DIST-MH-NGP", districtName: "Nagpur",          state: "Maharashtra",  districtHQ: "Nagpur",      isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dist004", districtCode: "DIST-MH-NSK", districtName: "Nashik",          state: "Maharashtra",  districtHQ: "Nashik",      isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dist005", districtCode: "DIST-GJ-AHM", districtName: "Ahmedabad",       state: "Gujarat",      districtHQ: "Ahmedabad",   isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dist006", districtCode: "DIST-GJ-VAD", districtName: "Vadodara",        state: "Gujarat",      districtHQ: "Vadodara",    isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dist007", districtCode: "DIST-GJ-SRT", districtName: "Surat",           state: "Gujarat",      districtHQ: "Surat",       isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dist008", districtCode: "DIST-KA-BLR", districtName: "Bengaluru Urban", state: "Karnataka",    districtHQ: "Bengaluru",   isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dist009", districtCode: "DIST-TN-CHN", districtName: "Chennai",         state: "Tamil Nadu",   districtHQ: "Chennai",     isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dist010", districtCode: "DIST-DL-NDL", districtName: "New Delhi",       state: "Delhi",        districtHQ: "New Delhi",   isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dist011", districtCode: "DIST-GJ-RAJ", districtName: "Rajkot",          state: "Gujarat",      districtHQ: "Rajkot",      isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dist012", districtCode: "DIST-MH-AUR", districtName: "Aurangabad",      state: "Maharashtra",  districtHQ: "Aurangabad",  isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dist013", districtCode: "DIST-TS-HYD", districtName: "Hyderabad",       state: "Telangana",    districtHQ: "Hyderabad",   isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dist014", districtCode: "DIST-KA-DHW", districtName: "Dharwad",         state: "Karnataka",    districtHQ: "Dharwad",     isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dist015", districtCode: "DIST-RJ-JDP", districtName: "Jodhpur",         state: "Rajasthan",    districtHQ: "Jodhpur",     isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dist016", districtCode: "DIST-UP-AGR", districtName: "Agra",            state: "Uttar Pradesh",districtHQ: "Agra",        isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dist017", districtCode: "DIST-TN-CBE", districtName: "Coimbatore",      state: "Tamil Nadu",   districtHQ: "Coimbatore",  isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dist018", districtCode: "DIST-WB-KOL", districtName: "Kolkata",         state: "West Bengal",  districtHQ: "Kolkata",     isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dist019", districtCode: "DIST-MP-IND", districtName: "Indore",          state: "Madhya Pradesh",districtHQ: "Indore",     isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dist020", districtCode: "DIST-MH-KOL", districtName: "Kolhapur",        state: "Maharashtra",  districtHQ: "Kolhapur",    isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
];

// ─── Village / Talukas ────────────────────────────────────────
export const SEED_VILLAGE_TALUKAS = [
  { id: "vlg001", villageCode: "VLG-001", villageName: "Haveli",       districtId: "dist001", districtName: "Pune",       pinCode: "412110", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "vlg002", villageCode: "VLG-002", villageName: "Mulshi",       districtId: "dist001", districtName: "Pune",       pinCode: "412108", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "vlg003", villageCode: "VLG-003", villageName: "Khed",         districtId: "dist001", districtName: "Pune",       pinCode: "410501", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "vlg004", villageCode: "VLG-004", villageName: "Shirur",       districtId: "dist001", districtName: "Pune",       pinCode: "412210", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "vlg005", villageCode: "VLG-005", villageName: "Savli",        districtId: "dist006", districtName: "Vadodara",   pinCode: "391770", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "vlg006", villageCode: "VLG-006", villageName: "Padra",        districtId: "dist006", districtName: "Vadodara",   pinCode: "391440", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "vlg007", villageCode: "VLG-007", villageName: "Daskroi",      districtId: "dist005", districtName: "Ahmedabad",  pinCode: "382470", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "vlg008", villageCode: "VLG-008", villageName: "Hingna",       districtId: "dist003", districtName: "Nagpur",     pinCode: "441110", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "vlg009", villageCode: "VLG-009", villageName: "Makarpura",    districtId: "dist006", districtName: "Vadodara",   pinCode: "390010", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "vlg010", villageCode: "VLG-010", villageName: "Pimpri",       districtId: "dist001", districtName: "Pune",       pinCode: "411018", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "vlg011", villageCode: "VLG-011", villageName: "Chakan",       districtId: "dist001", districtName: "Pune",       pinCode: "410501", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "vlg012", villageCode: "VLG-012", villageName: "Sanand",       districtId: "dist005", districtName: "Ahmedabad",  pinCode: "382110", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "vlg013", villageCode: "VLG-013", villageName: "Whitefield",   districtId: "dist008", districtName: "Bengaluru Urban", pinCode: "560066", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "vlg014", villageCode: "VLG-014", villageName: "Ambattur",     districtId: "dist009", districtName: "Chennai",    pinCode: "600053", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "vlg015", villageCode: "VLG-015", villageName: "Sinnar",       districtId: "dist004", districtName: "Nashik",     pinCode: "422103", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "vlg016", villageCode: "VLG-016", villageName: "Turbhe",       districtId: "dist002", districtName: "Mumbai",     pinCode: "400705", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "vlg017", villageCode: "VLG-017", villageName: "Vapi",         districtId: "dist007", districtName: "Surat",      pinCode: "396195", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "vlg018", villageCode: "VLG-018", villageName: "Aurangabad MIDC", districtId: "dist012", districtName: "Aurangabad", pinCode: "431003", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "vlg019", villageCode: "VLG-019", villageName: "Uppal",        districtId: "dist013", districtName: "Hyderabad",  pinCode: "500039", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "vlg020", villageCode: "VLG-020", villageName: "Peenya",       districtId: "dist008", districtName: "Bengaluru Urban", pinCode: "560058", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
];

// ─── Departments ──────────────────────────────────────────────
export const SEED_DEPARTMENTS = [
  { id: "dept001", departmentCode: "DEPT-001", departmentName: "Purchase",             departmentHead: "Rajesh Patil",    isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dept002", departmentCode: "DEPT-002", departmentName: "Production",           departmentHead: "Anil Kumar",      isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dept003", departmentCode: "DEPT-003", departmentName: "Quality Control",      departmentHead: "Priya Desai",     isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dept004", departmentCode: "DEPT-004", departmentName: "Accounts & Finance",   departmentHead: "Vikram Shah",     isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dept005", departmentCode: "DEPT-005", departmentName: "Human Resources",      departmentHead: "Neha Joshi",      isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dept006", departmentCode: "DEPT-006", departmentName: "Maintenance",          departmentHead: "Suresh Yadav",    isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dept007", departmentCode: "DEPT-007", departmentName: "Sales & Marketing",    departmentHead: "Arjun Mehta",     isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dept008", departmentCode: "DEPT-008", departmentName: "Stores & Logistics",   departmentHead: "Kiran Bhosale",   isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dept009", departmentCode: "DEPT-009", departmentName: "Design & Engineering", departmentHead: "Ramesh Nair",     isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "dept010", departmentCode: "DEPT-010", departmentName: "Information Technology", departmentHead: "Admin",         isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
];

// ─── Designations ─────────────────────────────────────────────
export const SEED_DESIGNATIONS = [
  { id: "desg001", designationCode: "DESG-001", designationName: "General Manager",         level: "L2", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "desg002", designationCode: "DESG-002", designationName: "Purchase Manager",        level: "L3", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "desg003", designationCode: "DESG-003", designationName: "Purchase Executive",      level: "L4", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "desg004", designationCode: "DESG-004", designationName: "Production Supervisor",   level: "L4", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "desg005", designationCode: "DESG-005", designationName: "Quality Inspector",       level: "L5", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "desg006", designationCode: "DESG-006", designationName: "Accounts Officer",        level: "L4", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "desg007", designationCode: "DESG-007", designationName: "HR Manager",              level: "L3", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "desg008", designationCode: "DESG-008", designationName: "Maintenance Technician",  level: "L5", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "desg009", designationCode: "DESG-009", designationName: "Sales Manager",           level: "L3", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "desg010", designationCode: "DESG-010", designationName: "Sales Executive",         level: "L5", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "desg011", designationCode: "DESG-011", designationName: "Stores Supervisor",       level: "L4", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "desg012", designationCode: "DESG-012", designationName: "Design Engineer",         level: "L4", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "desg013", designationCode: "DESG-013", designationName: "Production Operator",     level: "L6", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "desg014", designationCode: "DESG-014", designationName: "Maintenance Manager",     level: "L3", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "desg015", designationCode: "DESG-015", designationName: "Store Keeper",            level: "L6", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
];

// ─── Employees ────────────────────────────────────────────────
export const SEED_EMPLOYEES = [
  { id: "emp001", employeeId: "EMP-001", firstName: "Rajesh",   lastName: "Patil",    mobile: "9823456780", email: "rajesh.patil@speedinnovations.in",   departmentId: "dept001", departmentName: "Purchase",           designationId: "desg002", designationName: "Purchase Manager",      level: "L3", locationId: "loc007", locationName: "HR & Administration Block", employeeType: "Permanent", dateOfJoining: "2021-04-01", reportingManagerId: "emp020", reportingManagerName: "Lalit Tiwari", reportingManagerDept: "Production", reportingManagerLevel: "L2", reportingManagerDesignation: "General Manager", reportingManagerLocation: "loc001", status: "Active", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "emp002", employeeId: "EMP-002", firstName: "Sunita",   lastName: "Mehta",    mobile: "9867543211", email: "sunita.mehta@speedinnovations.in",   departmentId: "dept001", departmentName: "Purchase",           designationId: "desg003", designationName: "Purchase Executive",    level: "L4", locationId: "loc007", locationName: "HR & Administration Block", employeeType: "Permanent", dateOfJoining: "2022-07-15", reportingManagerId: "emp001", reportingManagerName: "Rajesh Patil",  reportingManagerDept: "Purchase",    reportingManagerLevel: "L3", reportingManagerDesignation: "Purchase Manager",  reportingManagerLocation: "loc007", status: "Active", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "emp003", employeeId: "EMP-003", firstName: "Anil",     lastName: "Kumar",    mobile: "9845022003", email: "anil.kumar@speedinnovations.in",     departmentId: "dept002", departmentName: "Production",         designationId: "desg004", designationName: "Production Supervisor", level: "L4", locationId: "loc001", locationName: "Production Floor Block A", employeeType: "Permanent", dateOfJoining: "2020-11-01", reportingManagerId: "emp020", reportingManagerName: "Lalit Tiwari", reportingManagerDept: "Production", reportingManagerLevel: "L2", reportingManagerDesignation: "General Manager", reportingManagerLocation: "loc001", status: "Active", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "emp004", employeeId: "EMP-004", firstName: "Priya",    lastName: "Desai",    mobile: "9765432104", email: "priya.desai@speedinnovations.in",    departmentId: "dept003", departmentName: "Quality Control",    designationId: "desg005", designationName: "Quality Inspector",     level: "L5", locationId: "loc006", locationName: "Quality & Testing Lab",   employeeType: "Permanent", dateOfJoining: "2023-02-20", reportingManagerId: "emp003", reportingManagerName: "Anil Kumar",   reportingManagerDept: "Production",  reportingManagerLevel: "L4", reportingManagerDesignation: "Production Supervisor", reportingManagerLocation: "loc001", status: "Active", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "emp005", employeeId: "EMP-005", firstName: "Vikram",   lastName: "Shah",     mobile: "9824011225", email: "vikram.shah@speedinnovations.in",    departmentId: "dept004", departmentName: "Accounts & Finance", designationId: "desg006", designationName: "Accounts Officer",      level: "L4", locationId: "loc007", locationName: "HR & Administration Block", employeeType: "Permanent", dateOfJoining: "2021-09-10", reportingManagerId: "emp020", reportingManagerName: "Lalit Tiwari", reportingManagerDept: "Production", reportingManagerLevel: "L2", reportingManagerDesignation: "General Manager", reportingManagerLocation: "loc001", status: "Active", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "emp006", employeeId: "EMP-006", firstName: "Neha",     lastName: "Joshi",    mobile: "9811033006", email: "neha.joshi@speedinnovations.in",     departmentId: "dept005", departmentName: "Human Resources",    designationId: "desg007", designationName: "HR Manager",            level: "L3", locationId: "loc007", locationName: "HR & Administration Block", employeeType: "Permanent", dateOfJoining: "2022-03-01", reportingManagerId: "emp020", reportingManagerName: "Lalit Tiwari", reportingManagerDept: "Production", reportingManagerLevel: "L2", reportingManagerDesignation: "General Manager", reportingManagerLocation: "loc001", status: "Active", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "emp007", employeeId: "EMP-007", firstName: "Suresh",   lastName: "Yadav",    mobile: "9820055007", email: "suresh.yadav@speedinnovations.in",   departmentId: "dept006", departmentName: "Maintenance",        designationId: "desg014", designationName: "Maintenance Manager",   level: "L3", locationId: "loc004", locationName: "Utility & Services Room", employeeType: "Permanent", dateOfJoining: "2019-06-15", reportingManagerId: "emp020", reportingManagerName: "Lalit Tiwari", reportingManagerDept: "Production", reportingManagerLevel: "L2", reportingManagerDesignation: "General Manager", reportingManagerLocation: "loc001", status: "Active", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "emp008", employeeId: "EMP-008", firstName: "Arjun",    lastName: "Mehta",    mobile: "9886077008", email: "arjun.mehta@speedinnovations.in",    departmentId: "dept007", departmentName: "Sales & Marketing",  designationId: "desg009", designationName: "Sales Manager",         level: "L3", locationId: "loc007", locationName: "HR & Administration Block", employeeType: "Permanent", dateOfJoining: "2022-01-10", reportingManagerId: "emp020", reportingManagerName: "Lalit Tiwari", reportingManagerDept: "Production", reportingManagerLevel: "L2", reportingManagerDesignation: "General Manager", reportingManagerLocation: "loc001", status: "Active", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "emp009", employeeId: "EMP-009", firstName: "Kiran",    lastName: "Bhosale",  mobile: "9822055009", email: "kiran.bhosale@speedinnovations.in",  departmentId: "dept008", departmentName: "Stores & Logistics", designationId: "desg011", designationName: "Stores Supervisor",     level: "L4", locationId: "loc005", locationName: "Warehouse & Dispatch Bay", employeeType: "Permanent", dateOfJoining: "2021-11-05", reportingManagerId: "emp020", reportingManagerName: "Lalit Tiwari", reportingManagerDept: "Production", reportingManagerLevel: "L2", reportingManagerDesignation: "General Manager", reportingManagerLocation: "loc001", status: "Active", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "emp010", employeeId: "EMP-010", firstName: "Ramesh",   lastName: "Nair",     mobile: "9845033010", email: "ramesh.nair@speedinnovations.in",    departmentId: "dept009", departmentName: "Design & Engineering", designationId: "desg012", designationName: "Design Engineer",     level: "L4", locationId: "loc008", locationName: "Design & Engineering Studio", employeeType: "Permanent", dateOfJoining: "2023-05-01", reportingManagerId: "emp020", reportingManagerName: "Lalit Tiwari", reportingManagerDept: "Production", reportingManagerLevel: "L2", reportingManagerDesignation: "General Manager", reportingManagerLocation: "loc001", status: "Active", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "emp011", employeeId: "EMP-011", firstName: "Mangesh",  lastName: "Patil",    mobile: "9765430011", email: "mangesh.patil@speedinnovations.in",  departmentId: "dept002", departmentName: "Production",         designationId: "desg013", designationName: "Production Operator",   level: "L6", locationId: "loc001", locationName: "Production Floor Block A", employeeType: "Contract",  dateOfJoining: "2023-09-01", reportingManagerId: "emp003", reportingManagerName: "Anil Kumar",   reportingManagerDept: "Production",  reportingManagerLevel: "L4", reportingManagerDesignation: "Production Supervisor", reportingManagerLocation: "loc001", status: "Active", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "emp012", employeeId: "EMP-012", firstName: "Dinesh",   lastName: "Raut",     mobile: "9823410012", email: "dinesh.raut@speedinnovations.in",    departmentId: "dept006", departmentName: "Maintenance",        designationId: "desg008", designationName: "Maintenance Technician",level: "L5", locationId: "loc004", locationName: "Utility & Services Room", employeeType: "Permanent", dateOfJoining: "2022-08-20", reportingManagerId: "emp007", reportingManagerName: "Suresh Yadav", reportingManagerDept: "Maintenance", reportingManagerLevel: "L3", reportingManagerDesignation: "Maintenance Manager", reportingManagerLocation: "loc004", status: "Active", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "emp013", employeeId: "EMP-013", firstName: "Kavita",   lastName: "Sharma",   mobile: "9811033013", email: "kavita.sharma@speedinnovations.in",  departmentId: "dept005", departmentName: "Human Resources",    designationId: "desg010", designationName: "Sales Executive",       level: "L5", locationId: "loc007", locationName: "HR & Administration Block", employeeType: "Permanent", dateOfJoining: "2024-01-15", reportingManagerId: "emp006", reportingManagerName: "Neha Joshi",   reportingManagerDept: "Human Resources", reportingManagerLevel: "L3", reportingManagerDesignation: "HR Manager", reportingManagerLocation: "loc007", status: "Active", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "emp014", employeeId: "EMP-014", firstName: "Rohit",    lastName: "Jha",      mobile: "9920100014", email: "rohit.jha@speedinnovations.in",      departmentId: "dept001", departmentName: "Purchase",           designationId: "desg003", designationName: "Purchase Executive",    level: "L4", locationId: "loc007", locationName: "HR & Administration Block", employeeType: "Permanent", dateOfJoining: "2023-06-01", reportingManagerId: "emp001", reportingManagerName: "Rajesh Patil", reportingManagerDept: "Purchase",    reportingManagerLevel: "L3", reportingManagerDesignation: "Purchase Manager",  reportingManagerLocation: "loc007", status: "Active", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "emp015", employeeId: "EMP-015", firstName: "Pooja",    lastName: "Bhand",    mobile: "9765432015", email: "pooja.bhand@speedinnovations.in",    departmentId: "dept003", departmentName: "Quality Control",    designationId: "desg005", designationName: "Quality Inspector",     level: "L5", locationId: "loc006", locationName: "Quality & Testing Lab",   employeeType: "Permanent", dateOfJoining: "2024-02-01", reportingManagerId: "emp004", reportingManagerName: "Priya Desai",  reportingManagerDept: "Quality Control", reportingManagerLevel: "L5", reportingManagerDesignation: "Quality Inspector", reportingManagerLocation: "loc006", status: "Active", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "emp016", employeeId: "EMP-016", firstName: "Santosh",  lastName: "More",     mobile: "9823400016", email: "santosh.more@speedinnovations.in",   departmentId: "dept008", departmentName: "Stores & Logistics", designationId: "desg015", designationName: "Store Keeper",          level: "L6", locationId: "loc005", locationName: "Warehouse & Dispatch Bay", employeeType: "Contract",  dateOfJoining: "2024-03-01", reportingManagerId: "emp009", reportingManagerName: "Kiran Bhosale", reportingManagerDept: "Stores & Logistics", reportingManagerLevel: "L4", reportingManagerDesignation: "Stores Supervisor", reportingManagerLocation: "loc005", status: "Active", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "emp017", employeeId: "EMP-017", firstName: "Yusuf",    lastName: "Sheikh",   mobile: "9867500017", email: "yusuf.sheikh@speedinnovations.in",   departmentId: "dept007", departmentName: "Sales & Marketing",  designationId: "desg010", designationName: "Sales Executive",       level: "L5", locationId: "loc007", locationName: "HR & Administration Block", employeeType: "Permanent", dateOfJoining: "2023-07-10", reportingManagerId: "emp008", reportingManagerName: "Arjun Mehta",  reportingManagerDept: "Sales & Marketing", reportingManagerLevel: "L3", reportingManagerDesignation: "Sales Manager", reportingManagerLocation: "loc007", status: "Active", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "emp018", employeeId: "EMP-018", firstName: "Ananya",   lastName: "Iyer",     mobile: "9845022018", email: "ananya.iyer@speedinnovations.in",    departmentId: "dept004", departmentName: "Accounts & Finance", designationId: "desg006", designationName: "Accounts Officer",      level: "L4", locationId: "loc007", locationName: "HR & Administration Block", employeeType: "Permanent", dateOfJoining: "2024-04-15", reportingManagerId: "emp005", reportingManagerName: "Vikram Shah",  reportingManagerDept: "Accounts & Finance", reportingManagerLevel: "L4", reportingManagerDesignation: "Accounts Officer", reportingManagerLocation: "loc007", status: "Active", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "emp019", employeeId: "EMP-019", firstName: "Ganesh",   lastName: "Kadam",    mobile: "9765400019", email: "ganesh.kadam@speedinnovations.in",   departmentId: "dept002", departmentName: "Production",         designationId: "desg013", designationName: "Production Operator",   level: "L6", locationId: "loc002", locationName: "Assembly Bay",             employeeType: "Contract",  dateOfJoining: "2024-01-08", reportingManagerId: "emp003", reportingManagerName: "Anil Kumar",   reportingManagerDept: "Production",  reportingManagerLevel: "L4", reportingManagerDesignation: "Production Supervisor", reportingManagerLocation: "loc001", status: "Active", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "emp020", employeeId: "EMP-020", firstName: "Lalit",    lastName: "Tiwari",   mobile: "9824011220", email: "lalit.tiwari@speedinnovations.in",   departmentId: "dept002", departmentName: "Production",         designationId: "desg001", designationName: "General Manager",       level: "L2", locationId: "loc001", locationName: "Production Floor Block A", employeeType: "Permanent", dateOfJoining: "2018-01-02", reportingManagerId: "",     reportingManagerName: "",             reportingManagerDept: "",            reportingManagerLevel: "", reportingManagerDesignation: "",                reportingManagerLocation: "",    status: "Active", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
];

// ─── Organisations ────────────────────────────────────────────
export const SEED_ORGANISATIONS = [
  { id: "org001", companyCode: "SI001", companyName: "Speed Innovations Pvt. Ltd.", companyLogo: "", companyWebsite: "https://speedinnovations.in", companyEmail: "info@speedinnovations.in", address: "Plot No. 14, GIDC Industrial Estate, Makarpura", zipcode: "390010", state: "Gujarat", city: "Vadodara", registrationNo: "U72900GJ2018PTC103456", gstNumber: "24AASSI1234A1Z5", type: "Head Office", timeZone: "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi", defaultCurrency: "INR", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "org002", companyCode: "SI002", companyName: "Speed Innovations — Pune Branch", companyLogo: "", companyWebsite: "https://speedinnovations.in", companyEmail: "pune@speedinnovations.in", address: "Gat No. 204, Chakan MIDC Phase II, Talegaon Road", zipcode: "410501", state: "Maharashtra", city: "Pune", registrationNo: "U72900MH2020PTC234567", gstNumber: "27AASSI5678B1Z3", type: "Branch", timeZone: "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi", defaultCurrency: "INR", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "org003", companyCode: "SI003", companyName: "Speed Innovations — Bangalore Branch", companyLogo: "", companyWebsite: "https://speedinnovations.in", companyEmail: "bangalore@speedinnovations.in", address: "3rd Floor, Tech Park One, Whitefield Main Road", zipcode: "560066", state: "Karnataka", city: "Bengaluru", registrationNo: "", gstNumber: "29AASSI9012C1Z1", type: "Branch", timeZone: "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi", defaultCurrency: "INR", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
];

// ─── Users ───────────────────────────────────────────────────
export const SEED_USERS = [
  { id: "u001", code: "U001", name: "Admin User",     email: "admin@speedinnovations.in",        password: "Admin@123", role: "Admin",   department: "IT",       mobile: "9800000001", isActive: true,  displayName: "Admin",    emailAddress: "admin@speedinnovations.in",        smtpServer: "", smtpPort: "587", smtpSSL: false, ccEmails: "", outlookEmail: false, fixLoginPC: "", createdAt: D, updatedAt: D, createdBy: "System", updatedBy: "System", changelog: [] },
  { id: "u002", code: "U002", name: "Arjun Mehta",    email: "arjun.mehta@speedinnovations.in",  password: "User@123",  role: "User",    department: "Sales",    mobile: "9800000002", isActive: true,  displayName: "Arjun M",  emailAddress: "arjun.mehta@speedinnovations.in",  smtpServer: "", smtpPort: "587", smtpSSL: false, ccEmails: "", outlookEmail: false, fixLoginPC: "", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: [] },
  { id: "u003", code: "U003", name: "Priya Sharma",   email: "priya.sharma@speedinnovations.in", password: "User@123",  role: "Manager", department: "Purchase", mobile: "9800000003", isActive: true,  displayName: "Priya S",  emailAddress: "priya.sharma@speedinnovations.in", smtpServer: "", smtpPort: "587", smtpSSL: false, ccEmails: "", outlookEmail: false, fixLoginPC: "", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: [] },
  { id: "u004", code: "U004", name: "Ramesh Patil",   email: "ramesh.patil@speedinnovations.in", password: "User@123",  role: "User",    department: "Purchase", mobile: "9800000004", isActive: true,  displayName: "Ramesh P", emailAddress: "ramesh.patil@speedinnovations.in", smtpServer: "", smtpPort: "587", smtpSSL: false, ccEmails: "", outlookEmail: false, fixLoginPC: "", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: [] },
];

// ─── Warehouses ───────────────────────────────────────────────
export const SEED_WAREHOUSES = [
  { id: "wh001", warehouseName: "Vadodara Main Store", warehouseCode: "WH-VAD-01", companyName: "Speed Innovations Pvt. Ltd.", gstNo: "24AASSI1234A1Z5", state: "Gujarat", city: "Vadodara", address1: "Plot No. 14, GIDC Industrial Estate", address2: "Makarpura", zipcode: "390010", contactName: "Kiran Bhosale", contactNumber: "9822055009", accessibleBranch: "Head Office", isActive: true, locations: [{ id: "whloc001", code: "VAD-MAIN", locationName: "Main Storage", parentId: null, isActive: true, isDefault: true }, { id: "whloc002", code: "VAD-RACK-A", locationName: "Rack A — Raw Materials", parentId: "whloc001", isActive: true, isDefault: false }, { id: "whloc003", code: "VAD-RACK-B", locationName: "Rack B — Spares", parentId: "whloc001", isActive: true, isDefault: false }, { id: "whloc004", code: "VAD-DISPATCH", locationName: "Dispatch Bay", parentId: null, isActive: true, isDefault: false }], remark: "Primary store for Vadodara plant. Manages raw material and spare inward/outward.", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "wh002", warehouseName: "Pune Distribution Centre", warehouseCode: "WH-PNQ-01", companyName: "Speed Innovations Pvt. Ltd.", gstNo: "27AASSI5678B1Z3", state: "Maharashtra", city: "Pune", address1: "Gat No. 204, Chakan MIDC Phase II", address2: "Talegaon Road", zipcode: "410501", contactName: "Santosh More", contactNumber: "9823400016", accessibleBranch: "Pune Branch", isActive: true, locations: [{ id: "whloc101", code: "PNQ-INWARD", locationName: "Inward Inspection", parentId: null, isActive: true, isDefault: true }, { id: "whloc102", code: "PNQ-STOCK", locationName: "Main Stock Floor", parentId: null, isActive: true, isDefault: false }, { id: "whloc103", code: "PNQ-DISPATCH", locationName: "Dispatch Staging", parentId: null, isActive: true, isDefault: false }], remark: "Pune plant store. Handles finished goods and WIP.", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
];

// ─── Business Units ───────────────────────────────────────────
export const SEED_BUSINESS_UNITS = [
  { id: "bu001", locationCode: "BU-VAD-01", contactName: "Rajesh Patel", contactNumber: "9824011223", address1: "Plot 14, GIDC Industrial Estate", address2: "Makarpura", state: "Gujarat", city: "Vadodara", zipcode: "390010", enableGst: true, gstNumber: "24AABCS4567K1Z3", ewayBillUsername: "speedit_vad", ewayBillPassword: "ewb@vad2024", einvoiceUsername: "speedit_vad_irp", einvoicePassword: "irp@vad2024", isActive: true, remark: "Head Office & registered GST unit for Gujarat.", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "bu002", locationCode: "BU-PNQ-01", contactName: "Anil Kumar",   contactNumber: "9845022003", address1: "Gat No. 204, Chakan MIDC Phase II", address2: "Talegaon Road", state: "Maharashtra", city: "Pune", zipcode: "410501", enableGst: true, gstNumber: "27AABCS4567K2Z1", ewayBillUsername: "speedit_pnq", ewayBillPassword: "ewb@pnq2024", einvoiceUsername: "", einvoicePassword: "", isActive: true, remark: "Pune manufacturing unit.", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "bu003", locationCode: "BU-BLR-01", contactName: "Arjun Mehta",  contactNumber: "9886077008", address1: "3rd Floor, Tech Park One", address2: "Whitefield Main Road", state: "Karnataka", city: "Bengaluru", zipcode: "560066", enableGst: true, gstNumber: "29AABCS4567K1Z4", ewayBillUsername: "", ewayBillPassword: "", einvoiceUsername: "", einvoicePassword: "", isActive: true, remark: "Bangalore sales & service unit.", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
];

// ─── Product Categories ───────────────────────────────────────
export const SEED_CATEGORIES = [
  { id: "cat1", code: "RM",   name: "Raw Material",   costMethod: "AVCO",     expenseAccount: "500010 — Raw Material Consumed", incomeAccount: "400010 — Domestic Sales" },
  { id: "cat2", code: "FG",   name: "Finished Goods", costMethod: "FIFO",     expenseAccount: "500020 — Finished Goods COGS",   incomeAccount: "400010 — Domestic Sales" },
  { id: "cat3", code: "CONS", name: "Consumables",    costMethod: "Standard", expenseAccount: "500030 — Consumables Expense",   incomeAccount: "" },
  { id: "cat4", code: "SVC",  name: "Services",       costMethod: "Standard", expenseAccount: "600010 — Service Cost",           incomeAccount: "400030 — Service Revenue" },
  { id: "cat5", code: "SEMI", name: "Semi-Finished",  costMethod: "AVCO",     expenseAccount: "500040 — WIP / Semi-Finished",   incomeAccount: "400020 — Export Sales" },
];

// ─── Products (legacy catalog) ────────────────────────────────
export const SEED_PRODUCTS = [
  { id: "3001", code: "P001", name: "MS Steel Rod 10mm",      isSold: true,  isPurchase: true,  isService: false, isStocked: true,  isManufactured: true,  invoicingPolicy: "Delivered Quantities", salesPrice: "75",    taxes: ["GST 18%"], cost: "62",    categoryCode: "RM",   categoryName: "Raw Material",   costMethod: "AVCO",     catExpenseAccount: "500010 — Raw Material Consumed", catIncomeAccount: "400010 — Domestic Sales", stockUOM: "KG",  internalNotes: "Store in covered dry area. Min dispatch: 100 KG.", variants: [], optionalProducts: [], accessoryProducts: [], alternativeProducts: [], conversions: [], purchaseDescription: "MS Steel Rod 10mm dia, IS:1786 Grade Fe415. Mill cert required.", incomeAccount: "400010 — Domestic Sales", expenseAccount: "500010 — Raw Material Consumed", isActive: true, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "3002", code: "P002", name: "Engine Oil 20W-50 (1L)", isSold: false, isPurchase: true,  isService: false, isStocked: true,  isManufactured: false, invoicingPolicy: "Delivered Quantities", salesPrice: "0",     taxes: ["GST 18%"], cost: "280",   categoryCode: "CONS", categoryName: "Consumables",    costMethod: "Standard", catExpenseAccount: "500030 — Consumables Expense",   catIncomeAccount: "",                        stockUOM: "LTR",internalNotes: "API SL grade. Store away from heat.", variants: [], optionalProducts: [], accessoryProducts: [], alternativeProducts: [], conversions: [], purchaseDescription: "Multi-grade engine oil 20W-50, 1L packs. API SL grade.", incomeAccount: "", expenseAccount: "500030 — Consumables Expense", isActive: true, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "3003", code: "P003", name: "Safety Helmet (HDPE)",   isSold: false, isPurchase: true,  isService: false, isStocked: true,  isManufactured: false, invoicingPolicy: "Delivered Quantities", salesPrice: "0",     taxes: ["GST 12%"], cost: "185",   categoryCode: "CONS", categoryName: "Consumables",    costMethod: "Standard", catExpenseAccount: "500030 — Consumables Expense",   catIncomeAccount: "",                        stockUOM: "NOS",internalNotes: "IS 2925 certified. Check expiry.", variants: [], optionalProducts: [], accessoryProducts: [], alternativeProducts: [], conversions: [], purchaseDescription: "HDPE safety helmet, IS 2925. Colour Yellow.", incomeAccount: "", expenseAccount: "500030 — Consumables Expense", isActive: true, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
];

// ─── Product Types ────────────────────────────────────────────
export const SEED_PRODUCT_TYPES = [
  { id: "pt001", typeId: "PT-001", name: "Raw Material",    isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pt002", typeId: "PT-002", name: "Finished Goods",  isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pt003", typeId: "PT-003", name: "Semi-Finished",   isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pt004", typeId: "PT-004", name: "Consumables",     isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pt005", typeId: "PT-005", name: "Spares & Tools",  isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
];

// ─── Product Sub-Types ────────────────────────────────────────
export const SEED_PRODUCT_SUBTYPES = [
  { id: "pst001", subtypeId: "PST-001", subtypeName: "Ferrous Metals",        productTypeId: "pt001", productTypeName: "Raw Material",  isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pst002", subtypeId: "PST-002", subtypeName: "Non-Ferrous Metals",    productTypeId: "pt001", productTypeName: "Raw Material",  isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pst003", subtypeId: "PST-003", subtypeName: "Polymers & Plastics",   productTypeId: "pt001", productTypeName: "Raw Material",  isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pst004", subtypeId: "PST-004", subtypeName: "Electrical Components", productTypeId: "pt001", productTypeName: "Raw Material",  isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pst005", subtypeId: "PST-005", subtypeName: "Assembled Units",       productTypeId: "pt002", productTypeName: "Finished Goods",isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pst006", subtypeId: "PST-006", subtypeName: "Lubricants & Chemicals",productTypeId: "pt004", productTypeName: "Consumables",   isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pst007", subtypeId: "PST-007", subtypeName: "Safety & PPE",          productTypeId: "pt004", productTypeName: "Consumables",   isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pst008", subtypeId: "PST-008", subtypeName: "Mechanical Spares",     productTypeId: "pt005", productTypeName: "Spares & Tools",isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pst009", subtypeId: "PST-009", subtypeName: "Machined Components",   productTypeId: "pt003", productTypeName: "Semi-Finished", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pst010", subtypeId: "PST-010", subtypeName: "Cutting Tools",         productTypeId: "pt005", productTypeName: "Spares & Tools",isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pst011", subtypeId: "PST-011", subtypeName: "Weldment Assemblies",   productTypeId: "pt003", productTypeName: "Semi-Finished", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pst012", subtypeId: "PST-012", subtypeName: "Electrical Spares",     productTypeId: "pt005", productTypeName: "Spares & Tools",isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
];

// ─── Product Masters ──────────────────────────────────────────
export const SEED_PRODUCT_MASTERS = [
  { id: "pm001", productCode: "RM-FE-001", productName: "MS Plate 10mm",                productTypeId: "pt001", productTypeName: "Raw Material",  subtypeId: "pst001", subtypeName: "Ferrous Metals",         units: "KGS", reorderLevel: "500",  description: "Mild Steel Plate 10mm thick, IS 2062 Grade E250. Width 1500mm.",                   isAsset: "No", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pm002", productCode: "RM-FE-002", productName: "MS Rod 12mm Fe500",            productTypeId: "pt001", productTypeName: "Raw Material",  subtypeId: "pst001", subtypeName: "Ferrous Metals",         units: "KGS", reorderLevel: "1000", description: "TMT Bar 12mm dia, IS 1786 Grade Fe500. Mill cert required.",                        isAsset: "No", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pm003", productCode: "RM-FE-003", productName: "Angle Iron 50x50x5mm",         productTypeId: "pt001", productTypeName: "Raw Material",  subtypeId: "pst001", subtypeName: "Ferrous Metals",         units: "KGS", reorderLevel: "300",  description: "Equal Angle Iron 50x50x5mm, IS 2062 Grade E250. Length 6 metres.",                 isAsset: "No", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pm004", productCode: "RM-FE-004", productName: "MS Channel 100x50mm",          productTypeId: "pt001", productTypeName: "Raw Material",  subtypeId: "pst001", subtypeName: "Ferrous Metals",         units: "KGS", reorderLevel: "200",  description: "Parallel flange channel ISMC 100, IS 808. Length 6 metres.",                        isAsset: "No", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pm005", productCode: "RM-FE-005", productName: "ERW Pipe 2 inch SCH40",        productTypeId: "pt001", productTypeName: "Raw Material",  subtypeId: "pst001", subtypeName: "Ferrous Metals",         units: "MTR", reorderLevel: "150",  description: "ERW Black Steel Pipe 2 inch Schedule 40, IS 1239 Part 1.",                         isAsset: "No", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pm006", productCode: "RM-NF-001", productName: "Copper Wire 2.5mm",            productTypeId: "pt001", productTypeName: "Raw Material",  subtypeId: "pst002", subtypeName: "Non-Ferrous Metals",     units: "MTR", reorderLevel: "200",  description: "Copper conductor wire 2.5mm², 1100V grade, IS 694.",                               isAsset: "No", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pm007", productCode: "RM-NF-002", productName: "Aluminium Sheet 2mm",          productTypeId: "pt001", productTypeName: "Raw Material",  subtypeId: "pst002", subtypeName: "Non-Ferrous Metals",     units: "KGS", reorderLevel: "100",  description: "Aluminium alloy sheet 2mm thick, 5052-H32. Size 1200x2400mm.",                     isAsset: "No", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pm008", productCode: "RM-NF-003", productName: "Brass Round Bar 25mm",         productTypeId: "pt001", productTypeName: "Raw Material",  subtypeId: "pst002", subtypeName: "Non-Ferrous Metals",     units: "KGS", reorderLevel: "50",   description: "Brass round bar 25mm dia, IS 319 Grade HV. Length 3 metres.",                      isAsset: "No", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pm009", productCode: "RM-POL-001", productName: "HDPE Pipe 50mm OD",           productTypeId: "pt001", productTypeName: "Raw Material",  subtypeId: "pst003", subtypeName: "Polymers & Plastics",    units: "MTR", reorderLevel: "100",  description: "HDPE pipe 50mm OD, SDR 11, IS 4984. Pressure rated 10 bar.",                       isAsset: "No", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pm010", productCode: "RM-ELE-001", productName: "PVC Insulated Wire 4sqmm",    productTypeId: "pt001", productTypeName: "Raw Material",  subtypeId: "pst004", subtypeName: "Electrical Components",  units: "MTR", reorderLevel: "500",  description: "FR PVC insulated wire 4sqmm, 1100V, IS 694. Red/Yellow/Blue/Green.",               isAsset: "No", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pm011", productCode: "RM-ELE-002", productName: "MCCB 3P 100A",               productTypeId: "pt001", productTypeName: "Raw Material",  subtypeId: "pst004", subtypeName: "Electrical Components",  units: "NOS", reorderLevel: "5",    description: "Moulded Case Circuit Breaker 3 Pole 100A, 10kA, IS/IEC 60947-2.",                 isAsset: "No", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pm012", productCode: "CONS-LUB-001", productName: "Engine Oil 20W-50 (1L)",   productTypeId: "pt004", productTypeName: "Consumables",   subtypeId: "pst006", subtypeName: "Lubricants & Chemicals", units: "LTR", reorderLevel: "50",   description: "Multi-grade engine oil for industrial equipment. API SL grade.",                    isAsset: "No", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pm013", productCode: "CONS-LUB-002", productName: "Hydraulic Oil ISO 68",      productTypeId: "pt004", productTypeName: "Consumables",   subtypeId: "pst006", subtypeName: "Lubricants & Chemicals", units: "LTR", reorderLevel: "100",  description: "Hydraulic oil ISO VG 68, anti-wear grade. 20L pails.",                             isAsset: "No", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pm014", productCode: "CONS-LUB-003", productName: "Grease SKF LGEP 2 (400g)", productTypeId: "pt004", productTypeName: "Consumables",   subtypeId: "pst006", subtypeName: "Lubricants & Chemicals", units: "NOS", reorderLevel: "20",   description: "Extreme pressure bearing grease, NLGI Grade 2. Cartridge 400g.",                   isAsset: "No", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pm015", productCode: "CONS-PPE-001", productName: "Safety Helmet HDPE",        productTypeId: "pt004", productTypeName: "Consumables",   subtypeId: "pst007", subtypeName: "Safety & PPE",           units: "NOS", reorderLevel: "20",   description: "HDPE safety helmet, IS 2925 certified. Colour: Yellow.",                           isAsset: "No", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pm016", productCode: "CONS-PPE-002", productName: "Safety Shoes Steel Toe",    productTypeId: "pt004", productTypeName: "Consumables",   subtypeId: "pst007", subtypeName: "Safety & PPE",           units: "PAIR",reorderLevel: "10",   description: "Steel toe safety shoes, IS 15298 Part 2 compliant. Sizes 6–11.",                   isAsset: "No", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pm017", productCode: "CONS-PPE-003", productName: "Nitrile Safety Gloves (M)", productTypeId: "pt004", productTypeName: "Consumables",   subtypeId: "pst007", subtypeName: "Safety & PPE",           units: "PAIR",reorderLevel: "50",   description: "Nitrile safety gloves, ISI marked. 100 pairs per box.",                            isAsset: "No", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pm018", productCode: "SP-MECH-001", productName: "Bearing 6205 ZZ",            productTypeId: "pt005", productTypeName: "Spares & Tools",subtypeId: "pst008", subtypeName: "Mechanical Spares",      units: "NOS", reorderLevel: "10",   description: "Deep groove ball bearing 6205 ZZ, 25x52x15mm. SKF or equivalent.",                 isAsset: "No", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pm019", productCode: "SP-MECH-002", productName: "V-Belt A-40",                productTypeId: "pt005", productTypeName: "Spares & Tools",subtypeId: "pst008", subtypeName: "Mechanical Spares",      units: "NOS", reorderLevel: "5",    description: "Classical V-belt, Section A, Inside length 40 inches. Gates or equivalent.",       isAsset: "No", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pm020", productCode: "SP-MECH-003", productName: "Oil Seal 35x52x8mm",         productTypeId: "pt005", productTypeName: "Spares & Tools",subtypeId: "pst008", subtypeName: "Mechanical Spares",      units: "NOS", reorderLevel: "10",   description: "Rotary shaft oil seal 35x52x8mm, NBR compound. SKF or equivalent.",               isAsset: "No", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pm021", productCode: "SP-CUT-001",  productName: "Carbide Insert CNMG 120408", productTypeId: "pt005", productTypeName: "Spares & Tools",subtypeId: "pst010", subtypeName: "Cutting Tools",          units: "NOS", reorderLevel: "20",   description: "Carbide turning insert CNMG 120408, Grade P25. Sandvik or equivalent.",            isAsset: "No", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pm022", productCode: "SP-ELE-001",  productName: "Contactor LC1D25 25A",       productTypeId: "pt005", productTypeName: "Spares & Tools",subtypeId: "pst012", subtypeName: "Electrical Spares",      units: "NOS", reorderLevel: "3",    description: "3-pole AC contactor 25A, 240V coil, IS/IEC 60947-4. Schneider LC1D25.",           isAsset: "No", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pm023", productCode: "SF-MCH-001",  productName: "CNC Turned Shaft 50mm",      productTypeId: "pt003", productTypeName: "Semi-Finished", subtypeId: "pst009", subtypeName: "Machined Components",    units: "NOS", reorderLevel: "5",    description: "CNC turned shaft 50mm dia x 300mm length, EN8 material, ground finish.",           isAsset: "No", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pm024", productCode: "SF-WLD-001",  productName: "Fabricated Frame Assembly",  productTypeId: "pt003", productTypeName: "Semi-Finished", subtypeId: "pst011", subtypeName: "Weldment Assemblies",    units: "NOS", reorderLevel: "2",    description: "Welded MS frame assembly 800x600x400mm, as per drg SI-WLD-001-Rev2.",              isAsset: "No", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "pm025", productCode: "FG-ASM-001",  productName: "Hydraulic Cylinder Assembly",productTypeId: "pt002", productTypeName: "Finished Goods",subtypeId: "pst005", subtypeName: "Assembled Units",        units: "NOS", reorderLevel: "1",    description: "Double acting hydraulic cylinder, 100T, stroke 500mm, as per drg SI-HYD-001.",   isAsset: "No", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
];

// ─── Vendors ──────────────────────────────────────────────────
const bk = (id, bankName, branch, city, accountNo, ifscCode) => ({ id, bankName, branch, city, accountNo, ifscCode, swiftCode: "", accountType: "Current" });
const cp = (id, name, designation, email, mobile) => ({ id, name, designation, email, mobile, landline: "", department: "" });
const tm = (id, line, term, description) => ({ id, line, term, description });

export const SEED_VENDORS = [
  { id: "v001", code: "V-A001", name: "Aditya Steel & Alloys Pvt Ltd",    group: "Manufacturer",    currency: "INR", isManufacturer: true,  isAgentDealer: false, isServiceJobwork: false, ledgerBalance: 245000, creditLimit: "500000", creditDays: "45", isDeactivated: false, reference: "ASA-2021", corporateAddress: "Plot No. 14, MIDC Industrial Area Phase II", corporateCountry: "India", corporateState: "Maharashtra", corporateCity: "Pune",      corporatePinCode: "411019", phone: "9823456780", email: "accounts@adityasteel.com",  website: "https://adityasteel.com", gstRegistrationStatus: "Registered", gstRegistrationNo: "27AABCA1234A1Z5", panNo: "AABCA1234A", msmeCategory: "",      msmeNo: "",                  contactPersons: [cp("cp1","Suresh Aditya","MD","suresh@adityasteel.com","9823456781"),cp("cp2","Priya Kulkarni","Accounts Mgr","priya@adityasteel.com","9823456782")], banks: [bk("b1","State Bank of India","MIDC Pune","Pune","32145678901","SBIN0012345")], terms: [tm("t1",1,"Payment","Net 45 days from invoice via NEFT/RTGS."),tm("t2",2,"Delivery","FOR destination within 21 working days from PO.")], remark: "Preferred vendor for structural steel. ISO 9001:2015 certified.", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "v002", code: "V-T001", name: "Technocraft Trading Co.",           group: "Trader",          currency: "INR", isManufacturer: false, isAgentDealer: true,  isServiceJobwork: false, ledgerBalance: 87500,  creditLimit: "200000", creditDays: "30", isDeactivated: false, reference: "TTC-022",  corporateAddress: "Shop No. 7, Gala Complex, LBS Road",         corporateCountry: "India", corporateState: "Maharashtra", corporateCity: "Mumbai",    corporatePinCode: "400086", phone: "9867543210", email: "info@technocraft.in",        website: "",                         gstRegistrationStatus: "Registered", gstRegistrationNo: "27AACCT5678B1Z3", panNo: "AACCT5678B", msmeCategory: "Small", msmeNo: "UDYAM-MH-27-0012345", contactPersons: [cp("cp3","Nikhil Teli","Proprietor","nikhil@technocraft.in","9867543211")], banks: [bk("b2","HDFC Bank","Mulund West","Mumbai","50100234567890","HDFC0001234")], terms: [tm("t3",1,"Payment","Net 30 days from invoice date.")], remark: "Reliable trader for electrical components and hardware.", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "v003", code: "V-S001", name: "SwiftLogix Services LLP",           group: "Service Provider",currency: "INR", isManufacturer: false, isAgentDealer: false, isServiceJobwork: true,  ledgerBalance: 32000,  creditLimit: "100000", creditDays: "15", isDeactivated: false, reference: "",         corporateAddress: "B-204, Solitaire Corporate Park, Chakala",   corporateCountry: "India", corporateState: "Maharashtra", corporateCity: "Mumbai",    corporatePinCode: "400093", phone: "9112345678", email: "billing@swiftlogix.in",     website: "",                         gstRegistrationStatus: "Registered", gstRegistrationNo: "27AALLS1234C1Z7", panNo: "AALLS1234C", msmeCategory: "Micro", msmeNo: "UDYAM-MH-27-0023456", contactPersons: [cp("cp4","Kavita Nair","Operations Head","kavita@swiftlogix.in","9112345679")], banks: [bk("b3","Axis Bank","Andheri East","Mumbai","920010012345678","UTIB0000123")], terms: [tm("t4",1,"Payment","Net 15 days from receipt of invoice.")], remark: "Handles all courier and freight forwarding.", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "v004", code: "V-I001", name: "Indo Gulf Impex",                   group: "Importer",        currency: "USD", isManufacturer: false, isAgentDealer: true,  isServiceJobwork: false, ledgerBalance: 610000, creditLimit: "1500000",creditDays: "60", isDeactivated: false, reference: "IGI-INT-09",corporateAddress: "Office 12, Trade Centre, BKC",                corporateCountry: "India", corporateState: "Maharashtra", corporateCity: "Mumbai",    corporatePinCode: "400051", phone: "9920123456", email: "trade@indogulf.com",         website: "https://indogulf.com",    gstRegistrationStatus: "SEZ",        gstRegistrationNo: "27AACIG7890D1Z1", panNo: "AACIG7890D", msmeCategory: "",      msmeNo: "",                  contactPersons: [cp("cp6","Farhan Sheikh","Director","farhan@indogulf.com","9920123457")], banks: [bk("b4","Citibank","BKC Mumbai","Mumbai","0123456789","CITI0000001")], terms: [tm("t7",1,"Payment","LC at sight or TT within 60 days of BL date.")], remark: "Import vendor — USD billing. LC required for orders above $50,000.", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "v005", code: "V-P001", name: "Pioneer Lubricants Pvt Ltd",        group: "Manufacturer",    currency: "INR", isManufacturer: true,  isAgentDealer: false, isServiceJobwork: false, ledgerBalance: 54000,  creditLimit: "150000", creditDays: "30", isDeactivated: false, reference: "PLB-2023", corporateAddress: "Survey No. 18, Bhosari MIDC",                 corporateCountry: "India", corporateState: "Maharashtra", corporateCity: "Pune",      corporatePinCode: "411026", phone: "9823400501", email: "sales@pioneerlube.in",       website: "https://pioneerlube.in",  gstRegistrationStatus: "Registered", gstRegistrationNo: "27AABCP2345F1Z2", panNo: "AABCP2345F", msmeCategory: "Small", msmeNo: "UDYAM-MH-27-0056789", contactPersons: [cp("cp8","Nitin Joshi","Sales Manager","nitin@pioneerlube.in","9823400502")], banks: [bk("b5","ICICI Bank","Bhosari","Pune","123456789001","ICIC0001234")], terms: [tm("t10",1,"Payment","Net 30 days from invoice. Discount 2% on advance payment.")], remark: "Approved vendor for all industrial lubricants. API certified products.", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "v006", code: "V-R001", name: "Rajputana Polymers Ltd",            group: "Manufacturer",    currency: "INR", isManufacturer: true,  isAgentDealer: false, isServiceJobwork: false, ledgerBalance: 28000,  creditLimit: "200000", creditDays: "45", isDeactivated: false, reference: "RPL-2022", corporateAddress: "Plot E-24, Sitapura Industrial Area",         corporateCountry: "India", corporateState: "Rajasthan",   corporateCity: "Jaipur",    corporatePinCode: "302022", phone: "9414567890", email: "orders@rajputanapolymers.com",website: "",                         gstRegistrationStatus: "Registered", gstRegistrationNo: "08AABCR3456G1Z8", panNo: "AABCR3456G", msmeCategory: "",      msmeNo: "",                  contactPersons: [cp("cp9","Vijay Agrawal","GM Sales","vijay@rajputanapolymers.com","9414567891")], banks: [bk("b6","Bank of Baroda","Sitapura","Jaipur","34512345678","BARB0SITAPU")], terms: [tm("t11",1,"Payment","Net 45 days. Freight extra at actuals.")], remark: "Supplier of HDPE/PP pipes, sheets and moulded parts.", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "v007", code: "V-E001", name: "Electra Components India Pvt Ltd",  group: "Manufacturer",    currency: "INR", isManufacturer: true,  isAgentDealer: false, isServiceJobwork: false, ledgerBalance: 112000, creditLimit: "300000", creditDays: "30", isDeactivated: false, reference: "ECI-2022", corporateAddress: "Old No. 12, New No. 25, SIDCO Industrial Estate,Ambattur", corporateCountry: "India", corporateState: "Tamil Nadu",  corporateCity: "Chennai",   corporatePinCode: "600098", phone: "9841234560", email: "sales@electracomponents.in",website: "https://electracomponents.in",gstRegistrationStatus: "Registered",gstRegistrationNo: "33AABCE4567H1Z6", panNo: "AABCE4567H", msmeCategory: "Medium",msmeNo: "",                  contactPersons: [cp("cp10","Balasubramanian R","DGM Sales","bala@electracomponents.in","9841234561")], banks: [bk("b7","Canara Bank","Ambattur","Chennai","5678901234","CNRB0001234")], terms: [tm("t12",1,"Payment","30 days from date of invoice. Part delivery acceptable.")], remark: "Approved vendor for contactors, MCCBs, and wiring accessories. L&T and Schneider authorised distributor.", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "v008", code: "V-B001", name: "Bharat Forge Ancillaries Ltd",      group: "Manufacturer",    currency: "INR", isManufacturer: true,  isAgentDealer: false, isServiceJobwork: false, ledgerBalance: 176000, creditLimit: "400000", creditDays: "45", isDeactivated: false, reference: "BFA-2020", corporateAddress: "Gate No. 1, Mundhwa Industrial Area",         corporateCountry: "India", corporateState: "Maharashtra", corporateCity: "Pune",      corporatePinCode: "411036", phone: "9823109876", email: "spares@bharatforge-ancillaries.com",website:"",gstRegistrationStatus: "Registered",gstRegistrationNo: "27AABCB5678I1Z4", panNo: "AABCB5678I", msmeCategory: "",      msmeNo: "",                  contactPersons: [cp("cp11","Sandesh Kulkarni","Sr Manager","sandesh@bfa.com","9823109877")], banks: [bk("b8","Punjab National Bank","Mundhwa","Pune","4567890123","PUNB0123456")], terms: [tm("t13",1,"Payment","45 days net. Forge components as per approved drawings only.")], remark: "Critical vendor for precision forgings and machined components.", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "v009", code: "V-C001", name: "Eastern Copper Wires Ltd",          group: "Manufacturer",    currency: "INR", isManufacturer: true,  isAgentDealer: false, isServiceJobwork: false, ledgerBalance: 68000,  creditLimit: "250000", creditDays: "30", isDeactivated: false, reference: "ECW-2023", corporateAddress: "34/2A, Taratola Road, Santragachi",          corporateCountry: "India", corporateState: "West Bengal", corporateCity: "Kolkata",   corporatePinCode: "711104", phone: "9830456780", email: "mktg@easterncopper.com",     website: "",                         gstRegistrationStatus: "Registered", gstRegistrationNo: "19AABCE6789J1Z2", panNo: "AABCE6789J", msmeCategory: "",      msmeNo: "",                  contactPersons: [cp("cp12","Dibyendu Das","Marketing Head","dibyendu@easterncopper.com","9830456781")], banks: [bk("b9","Bandhan Bank","Santragachi","Kolkata","1234567890123","BDBL0000123")], terms: [tm("t14",1,"Payment","30 days from invoice. Prices subject to LME copper rate fluctuations.")], remark: "Supplier of copper and aluminium wires and conductors. LME-linked pricing.", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "v010", code: "V-G001", name: "Gujarat Gas & Welding Supplies",    group: "Trader",          currency: "INR", isManufacturer: false, isAgentDealer: true,  isServiceJobwork: false, ledgerBalance: 21000,  creditLimit: "100000", creditDays: "15", isDeactivated: false, reference: "GGW-2024", corporateAddress: "Shop 4, Harinagar Society, Makarpura Road",   corporateCountry: "India", corporateState: "Gujarat",     corporateCity: "Vadodara",  corporatePinCode: "390010", phone: "9824001234", email: "ggws@yahoo.in",              website: "",                         gstRegistrationStatus: "Registered", gstRegistrationNo: "24AABCG7890K1Z9", panNo: "AABCG7890K", msmeCategory: "Micro", msmeNo: "UDYAM-GJ-24-0034567", contactPersons: [cp("cp13","Hardik Patel","Owner","hardik@ggws.in","9824001235")], banks: [bk("b10","Bank of India","Makarpura","Vadodara","6789012345","BKID0001234")], terms: [tm("t15",1,"Payment","15 days net. Gas cylinders on deposit; refundable on return.")], remark: "Local vendor for welding gases (O2, Acetylene, CO2, Argon) and welding consumables.", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
];

// ─── Customers ────────────────────────────────────────────────
export const SEED_CUSTOMERS = [
  { id: "c001", code: "C-A001", name: "Tata Motors Ltd",                   group: "OEM",             currency: "INR", ledgerBalance: 780000, creditLimit: "5000000", creditDays: "45", isDeactivated: false, reference: "TML-PNQ",  corporateAddress: "Bombay House, 24 Homi Mody Street, Fort", corporateCountry: "India", corporateState: "Maharashtra", corporateCity: "Mumbai",    corporatePinCode: "400001", phone: "9820011111", email: "procurement@tatamotors.com",gstRegistrationNo: "27AAACT2727Q1ZV", panNo: "AAACT2727Q", gstRegistrationStatus: "Registered", industry: "Manufacturing", segment: "Large Enterprise", salesperson: "Arjun Mehta",  contactPersons: [cp("cc1","Sunil Bhide","Purchase Manager","sunil.bhide@tatamotors.com","9820011113")], banks: [bk("cb1","State Bank of India","Fort Mumbai","Mumbai","10012345678","SBIN0000300")], terms: [tm("ct1",1,"Payment","Net 45 days. TDS applicable per IT Act.")], remark: "Strategic OEM customer. BG required for orders above Rs 25 lakhs.", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "c002", code: "C-A002", name: "Mahindra & Mahindra Ltd",           group: "OEM",             currency: "INR", ledgerBalance: 320000, creditLimit: "3000000", creditDays: "45", isDeactivated: false, reference: "MML-CHK",  corporateAddress: "Mahindra Towers, Dr. G.M. Bhosale Marg, Worli", corporateCountry: "India", corporateState: "Maharashtra", corporateCity: "Mumbai",    corporatePinCode: "400018", phone: "9820022222", email: "procurement@mahindra.com",  gstRegistrationNo: "27AAACM3227A1ZA", panNo: "AAACM3227A", gstRegistrationStatus: "Registered", industry: "Automotive",     segment: "Large Enterprise", salesperson: "Arjun Mehta",  contactPersons: [cp("cc2","Ramakant Desai","Sr. Purchase Manager","ramakant.desai@mahindra.com","9820022223")], banks: [bk("cb2","HDFC Bank","Worli","Mumbai","50100567890123","HDFC0000456")], terms: [tm("ct2",1,"Payment","Net 45 days from invoice. Credit note cycle monthly.")], remark: "Long-term OEM partnership. Annual rate contract renewal in April.", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "c003", code: "C-A003", name: "Larsen & Toubro Ltd",               group: "EPC Contractor",  currency: "INR", ledgerBalance: 560000, creditLimit: "4000000", creditDays: "60", isDeactivated: false, reference: "LNT-HVY",  corporateAddress: "L&T House, Ballard Estate",               corporateCountry: "India", corporateState: "Maharashtra", corporateCity: "Mumbai",    corporatePinCode: "400001", phone: "9820033333", email: "procurement.heavy@lntecc.com",gstRegistrationNo: "27AAACL3596K1ZU", panNo: "AAACL3596K", gstRegistrationStatus: "Registered", industry: "Engineering",    segment: "Large Enterprise", salesperson: "Yusuf Sheikh", contactPersons: [cp("cc3","Prashant Kelkar","Chief Procurement","prashant.kelkar@lntecc.com","9820033334")], banks: [bk("cb3","Axis Bank","Ballard Estate","Mumbai","914020045678901","UTIB0000456")], terms: [tm("ct3",1,"Payment","60 days from invoice. Interim billing allowed on milestones.")], remark: "EPC contractor. Orders tied to project schedules. PO terms strictly followed.", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "c004", code: "C-A004", name: "BHEL — Bhopal Works",               group: "Public Sector",   currency: "INR", ledgerBalance: 0,      creditLimit: "2000000", creditDays: "90", isDeactivated: false, reference: "BHEL-BPL", corporateAddress: "BHEL Township, Piplani",                   corporateCountry: "India", corporateState: "Madhya Pradesh",corporateCity: "Bhopal",    corporatePinCode: "462022", phone: "9425123456", email: "procurement@bhelbpl.co.in",gstRegistrationNo: "23AAACB0472E1ZK", panNo: "AAACB0472E", gstRegistrationStatus: "Registered", industry: "Heavy Engineering",segment: "Government",       salesperson: "Yusuf Sheikh", contactPersons: [cp("cc4","B.K. Sharma","DGM Purchase","bk.sharma@bhelbpl.co.in","9425123457")], banks: [bk("cb4","State Bank of India","BHEL Piplani","Bhopal","52000123456","SBIN0030456")], terms: [tm("ct4",1,"Payment","90 days from certified invoice. Advance 10% against PO.")], remark: "PSU customer. All invoices need countersignature. TDS mandatory.", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "c005", code: "C-A005", name: "Kirloskar Brothers Ltd",             group: "OEM",             currency: "INR", ledgerBalance: 145000, creditLimit: "1000000", creditDays: "45", isDeactivated: false, reference: "KBL-KOP",  corporateAddress: "Udyog Bhavan, Tilak Road, Kirloskarwadi",  corporateCountry: "India", corporateState: "Maharashtra", corporateCity: "Kolhapur",  corporatePinCode: "416308", phone: "9822045678", email: "procurement@kirloskar.com", gstRegistrationNo: "27AAACK2847D1ZP", panNo: "AAACK2847D", gstRegistrationStatus: "Registered", industry: "Manufacturing",  segment: "Large Enterprise", salesperson: "Arjun Mehta",  contactPersons: [cp("cc5","Anand Kulkarni","Purchase Manager","anand.kulkarni@kirloskar.com","9822045679")], banks: [bk("cb5","ICICI Bank","Kolhapur","123456789056","ICIC0000789")], terms: [tm("ct5",1,"Payment","45 days from invoice. Annual rate contract preferred.")], remark: "OEM for pump components. Quality control stringent — PPAP mandatory for new parts.", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "c006", code: "C-A006", name: "Godrej Industries Ltd",              group: "Conglomerate",    currency: "INR", ledgerBalance: 230000, creditLimit: "1500000", creditDays: "30", isDeactivated: false, reference: "GIL-MUM",  corporateAddress: "Pirojshanagar, Eastern Express Highway",   corporateCountry: "India", corporateState: "Maharashtra", corporateCity: "Mumbai",    corporatePinCode: "400079", phone: "9820044444", email: "indus.procurement@godrej.com",gstRegistrationNo: "27AAACG2909G1ZJ", panNo: "AAACG2909G", gstRegistrationStatus: "Registered", industry: "Manufacturing",  segment: "Large Enterprise", salesperson: "Yusuf Sheikh", contactPersons: [cp("cc6","Manisha Iyer","Materials Manager","manisha.iyer@godrej.com","9820044445")], banks: [bk("cb6","Bank of India","Vikhroli","Mumbai","234567890123","BKID0000789")], terms: [tm("ct6",1,"Payment","30 days from invoice. GST invoice mandatory.")], remark: "Diversified customer — orders from multiple divisions. Raise separate POs per division.", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "c007", code: "C-A007", name: "Infosys BPO Solutions Ltd",          group: "Corporate",       currency: "INR", ledgerBalance: 325000, creditLimit: "1000000", creditDays: "60", isDeactivated: false, reference: "IBS-2022", corporateAddress: "Plot No. 44, Electronics City Phase I",    corporateCountry: "India", corporateState: "Karnataka",   corporateCity: "Bengaluru", corporatePinCode: "560100", phone: "9845012345", email: "accounts@infosysbpo.com",    gstRegistrationNo: "29AACCI1234B1Z3", panNo: "AACCI1234B", gstRegistrationStatus: "Registered", industry: "IT & Technology",segment: "Large Enterprise", salesperson: "Arjun Mehta",  contactPersons: [cp("cc7","Sneha Krishnan","Finance Manager","sneha.k@infosysbpo.com","9845012346")], banks: [bk("cb7","HDFC Bank","Electronic City","Bengaluru","50100123456789","HDFC0001001")], terms: [tm("ct7",1,"Payment","60 days from invoice via NEFT/RTGS.")], remark: "Annual AMC contract. Renewal in March.", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "c008", code: "C-A008", name: "Maharashtra PWD",                    group: "Government",      currency: "INR", ledgerBalance: 0,      creditLimit: "2000000", creditDays: "90", isDeactivated: false, reference: "MPWD-2024",corporateAddress: "PWD Bhavan, Mazgaon",                       corporateCountry: "India", corporateState: "Maharashtra", corporateCity: "Mumbai",    corporatePinCode: "400010", phone: "9920100200", email: "procurement@mpwd.gov.in",   gstRegistrationNo: "27AAAAG1234A1ZP", panNo: "AAAAG1234A", gstRegistrationStatus: "Exempt",    industry: "Construction",   segment: "Government",       salesperson: "Yusuf Sheikh", contactPersons: [cp("cc8","Rajesh Kamble","Asst. Engineer","rajesh.kamble@mpwd.gov.in","9920100201")], banks: [], terms: [tm("ct8",1,"Payment","90 days via government treasury after certified bill submission.")], remark: "Government customer — exempt from GST. All invoices need AE countersign.", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "c009", code: "C-A009", name: "Thermax Ltd",                        group: "OEM",             currency: "INR", ledgerBalance: 195000, creditLimit: "1200000", creditDays: "45", isDeactivated: false, reference: "TML-PNQ2", corporateAddress: "14 Mumbai–Pune Road, Wakdewadi",            corporateCountry: "India", corporateState: "Maharashtra", corporateCity: "Pune",      corporatePinCode: "411003", phone: "9823055678", email: "scm@thermaxglobal.com",     gstRegistrationNo: "27AAACT2345T1ZB", panNo: "AAACT2345T", gstRegistrationStatus: "Registered", industry: "Industrial Equipment",segment:"Large Enterprise",  salesperson: "Arjun Mehta",  contactPersons: [cp("cc9","Abhijit Deshpande","SCM Head","abhijit.d@thermaxglobal.com","9823055679")], banks: [bk("cb9","Axis Bank","Wakdewadi","Pune","914020056789012","UTIB0000789")], terms: [tm("ct9",1,"Payment","45 days. Inspection at our works before dispatch.")], remark: "Quality-conscious OEM. PDI required for all machined parts.", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "c010", code: "C-A010", name: "Global Tech Exports LLC",             group: "Export",          currency: "USD", ledgerBalance: 0,      creditLimit: "3000000", creditDays: "60", isDeactivated: true,  reference: "GTE-2023", corporateAddress: "Office 901, Al Sila Tower, ADGM Square",   corporateCountry: "UAE",   corporateState: "Abu Dhabi",   corporateCity: "Abu Dhabi", corporatePinCode: "",       phone: "+971501234567",email: "orders@globaltechexports.ae",gstRegistrationNo: "",               panNo: "",           gstRegistrationStatus: "Unregistered",industry: "Trading",       segment: "MNC",              salesperson: "Arjun Mehta",  contactPersons: [cp("cc10","James Walker","CEO","james@globaltechexports.ae","+971501234568")], banks: [bk("cb10","HSBC Bank","ADGM Branch","Abu Dhabi","AE070331234567890123456","")], terms: [tm("ct10",1,"Payment","LC at sight or advance TT for orders above USD 50,000.")], remark: "Deactivated — contract lapsed Dec 2024. Reactivate only after new agreement.", createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
];
