const C = (ts) => [{ timestamp: ts, user: "Admin", action: "Created", changes: "Record created" }];
const D = "2024-01-05T09:00:00.000Z";
const A = "2024-01-15T09:00:00.000Z";

// ─── Work Order Types ─────────────────────────────────────────
export const SEED_WORK_ORDER_TYPES = [
  { id: "wot001", typeId: "WOT-00001", typeName: "Manufacturing Order",          description: "Standard production run for finished goods",         requiresApproval: false, isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "wot002", typeId: "WOT-00002", typeName: "Repair Order",                 description: "Asset or equipment breakdown repair",                requiresApproval: true,  isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "wot003", typeId: "WOT-00003", typeName: "Job Work Order",               description: "Outsourced machining or fabrication operations",      requiresApproval: true,  isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "wot004", typeId: "WOT-00004", typeName: "Preventive Maintenance Order", description: "Scheduled PM activities per maintenance calendar",    requiresApproval: false, isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "wot005", typeId: "WOT-00005", typeName: "Rework Order",                 description: "Correction of defective or non-conforming products", requiresApproval: false, isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
];

// ─── Unit Types ───────────────────────────────────────────────
export const SEED_UNIT_TYPES = [
  { id: "ut001", unitTypeId: "UT-00001", unitTypeName: "Weight",      isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "ut002", unitTypeId: "UT-00002", unitTypeName: "Length",      isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "ut003", unitTypeId: "UT-00003", unitTypeName: "Volume",      isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "ut004", unitTypeId: "UT-00004", unitTypeName: "Count / Nos", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "ut005", unitTypeId: "UT-00005", unitTypeName: "Time",        isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "ut006", unitTypeId: "UT-00006", unitTypeName: "Area",        isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "ut007", unitTypeId: "UT-00007", unitTypeName: "Pair / Set",  isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
];

// ─── Units of Measure ─────────────────────────────────────────
export const SEED_UOM = [
  { id: "uom001", unitId: "UOM-00001", unitTypeId: "ut001", unitTypeName: "Weight",      unitName: "Kilogram",    unitShortCode: "KGS",  isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "uom002", unitId: "UOM-00002", unitTypeId: "ut001", unitTypeName: "Weight",      unitName: "Gram",        unitShortCode: "GRM",  isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "uom003", unitId: "UOM-00003", unitTypeId: "ut001", unitTypeName: "Weight",      unitName: "Metric Ton",  unitShortCode: "TON",  isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "uom004", unitId: "UOM-00004", unitTypeId: "ut002", unitTypeName: "Length",      unitName: "Metre",       unitShortCode: "MTR",  isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "uom005", unitId: "UOM-00005", unitTypeId: "ut002", unitTypeName: "Length",      unitName: "Millimetre",  unitShortCode: "MM",   isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "uom006", unitId: "UOM-00006", unitTypeId: "ut002", unitTypeName: "Length",      unitName: "Feet",        unitShortCode: "FT",   isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "uom007", unitId: "UOM-00007", unitTypeId: "ut003", unitTypeName: "Volume",      unitName: "Litre",       unitShortCode: "LTR",  isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "uom008", unitId: "UOM-00008", unitTypeId: "ut003", unitTypeName: "Volume",      unitName: "Millilitre",  unitShortCode: "ML",   isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "uom009", unitId: "UOM-00009", unitTypeId: "ut004", unitTypeName: "Count / Nos", unitName: "Numbers",     unitShortCode: "NOS",  isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "uom010", unitId: "UOM-00010", unitTypeId: "ut004", unitTypeName: "Count / Nos", unitName: "Set",         unitShortCode: "SET",  isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "uom011", unitId: "UOM-00011", unitTypeId: "ut004", unitTypeName: "Count / Nos", unitName: "Packet",      unitShortCode: "PKT",  isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "uom012", unitId: "UOM-00012", unitTypeId: "ut005", unitTypeName: "Time",        unitName: "Hour",        unitShortCode: "HRS",  isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "uom013", unitId: "UOM-00013", unitTypeId: "ut007", unitTypeName: "Pair / Set",  unitName: "Pair",        unitShortCode: "PAIR", isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "uom014", unitId: "UOM-00014", unitTypeId: "ut006", unitTypeName: "Area",        unitName: "Square Metre",unitShortCode: "SQM",  isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
  { id: "uom015", unitId: "UOM-00015", unitTypeId: "ut002", unitTypeName: "Length",      unitName: "Centimetre",  unitShortCode: "CM",   isDeactivated: false, createdAt: D, updatedAt: D, createdBy: "Admin", updatedBy: "Admin", changelog: C(D) },
];

// ─── Asset Structures (Locations) ─────────────────────────────
const L = "2024-01-10T09:00:00.000Z";
export const SEED_ASSET_STRUCTURES = [
  { id: "loc001", locationId: "LOC-001", locationName: "Production Floor Block A",      site: "Main Plant",       warehouseId: "wh001", warehouseName: "Vadodara Main Store",         createdAt: L, updatedAt: L, createdBy: "Admin", updatedBy: "Admin", changelog: C(L) },
  { id: "loc002", locationId: "LOC-002", locationName: "Assembly Bay",                  site: "Main Plant",       warehouseId: "wh001", warehouseName: "Vadodara Main Store",         createdAt: L, updatedAt: L, createdBy: "Admin", updatedBy: "Admin", changelog: C(L) },
  { id: "loc003", locationId: "LOC-003", locationName: "Compressor House",              site: "Utility Block",    warehouseId: "",      warehouseName: "",                            createdAt: L, updatedAt: L, createdBy: "Admin", updatedBy: "Admin", changelog: C(L) },
  { id: "loc004", locationId: "LOC-004", locationName: "Utility & Services Room",       site: "Utility Block",    warehouseId: "",      warehouseName: "",                            createdAt: L, updatedAt: L, createdBy: "Admin", updatedBy: "Admin", changelog: C(L) },
  { id: "loc005", locationId: "LOC-005", locationName: "Warehouse & Dispatch Bay",      site: "Main Plant",       warehouseId: "wh001", warehouseName: "Vadodara Main Store",         createdAt: L, updatedAt: L, createdBy: "Admin", updatedBy: "Admin", changelog: C(L) },
  { id: "loc006", locationId: "LOC-006", locationName: "Quality & Testing Lab",         site: "Main Plant",       warehouseId: "",      warehouseName: "",                            createdAt: L, updatedAt: L, createdBy: "Admin", updatedBy: "Admin", changelog: C(L) },
  { id: "loc007", locationId: "LOC-007", locationName: "HR & Administration Block",     site: "Main Plant",       warehouseId: "",      warehouseName: "",                            createdAt: L, updatedAt: L, createdBy: "Admin", updatedBy: "Admin", changelog: C(L) },
  { id: "loc008", locationId: "LOC-008", locationName: "Design & Engineering Studio",   site: "Main Plant",       warehouseId: "",      warehouseName: "",                            createdAt: L, updatedAt: L, createdBy: "Admin", updatedBy: "Admin", changelog: C(L) },
  { id: "loc009", locationId: "LOC-009", locationName: "Machine Shop",                  site: "Main Plant",       warehouseId: "",      warehouseName: "",                            createdAt: L, updatedAt: L, createdBy: "Admin", updatedBy: "Admin", changelog: C(L) },
  { id: "loc010", locationId: "LOC-010", locationName: "Paint Shop & Surface Treatment",site: "Main Plant",       warehouseId: "",      warehouseName: "",                            createdAt: L, updatedAt: L, createdBy: "Admin", updatedBy: "Admin", changelog: C(L) },
];

// ─── Assets ───────────────────────────────────────────────────
export const SEED_ASSETS = [
  { id: "ast001", assetId: "AST-001", name: "CNC Machining Centre",          locationId: "loc001", locationName: "Production Floor Block A",       assetTypeId: "", assetTypeName: "Machinery",         manufacturer: "BFW India",         modelNo: "BFW-CNC-VF4",    serialNo: "BFW2021031401",   installationDate: "2021-03-14", warrantyDetails: "5 years expires Mar 2026",  level: "1", status: "Active",            consumedHours: "4820",  createdAt: A, updatedAt: A, createdBy: "Admin", updatedBy: "Admin", changelog: C(A) },
  { id: "ast002", assetId: "AST-002", name: "Air Compressor 150 CFM",        locationId: "loc003", locationName: "Compressor House",                assetTypeId: "", assetTypeName: "Compressed Air",    manufacturer: "Atlas Copco",       modelNo: "GA37VSD",        serialNo: "AC20190827A3",    installationDate: "2019-08-27", warrantyDetails: "3 years expired Aug 2022",  level: "1", status: "Active",            consumedHours: "12453", createdAt: A, updatedAt: A, createdBy: "Admin", updatedBy: "Admin", changelog: C(A) },
  { id: "ast003", assetId: "AST-003", name: "DG Set 250 kVA",                locationId: "loc004", locationName: "Utility & Services Room",         assetTypeId: "", assetTypeName: "Electrical",        manufacturer: "Cummins India",     modelNo: "C250D5",         serialNo: "CUM220503B1",     installationDate: "2022-05-03", warrantyDetails: "2 years expired May 2024",  level: "1", status: "Active",            consumedHours: "3204",  createdAt: A, updatedAt: A, createdBy: "Admin", updatedBy: "Admin", changelog: C(A) },
  { id: "ast004", assetId: "AST-004", name: "Conveyor Belt System",           locationId: "loc002", locationName: "Assembly Bay",                    assetTypeId: "", assetTypeName: "Material Handling", manufacturer: "FlexLink",          modelNo: "XK-45",          serialNo: "FL2020110401",    installationDate: "2020-11-04", warrantyDetails: "2 years expired Nov 2022",  level: "1", status: "Active",            consumedHours: "18600", createdAt: A, updatedAt: A, createdBy: "Admin", updatedBy: "Admin", changelog: C(A) },
  { id: "ast005", assetId: "AST-005", name: "Hydraulic Press 100T",           locationId: "loc001", locationName: "Production Floor Block A",       assetTypeId: "", assetTypeName: "Machinery",         manufacturer: "Hydropack",         modelNo: "HP-100T",        serialNo: "HP2018060201",    installationDate: "2018-06-02", warrantyDetails: "3 years expired Jun 2021",  level: "1", status: "Under Maintenance", consumedHours: "22309", createdAt: A, updatedAt: A, createdBy: "Admin", updatedBy: "Admin", changelog: C(A) },
  { id: "ast006", assetId: "AST-006", name: "EOT Overhead Crane 5T",          locationId: "loc002", locationName: "Assembly Bay",                    assetTypeId: "", assetTypeName: "Material Handling", manufacturer: "Indef",             modelNo: "EOT-5T-A",       serialNo: "INDEF230704C2",   installationDate: "2023-07-04", warrantyDetails: "2 years expires Jul 2025",  level: "1", status: "Active",            consumedHours: "1870",  createdAt: A, updatedAt: A, createdBy: "Admin", updatedBy: "Admin", changelog: C(A) },
  { id: "ast007", assetId: "AST-007", name: "CNC Lathe LT-28",                locationId: "loc009", locationName: "Machine Shop",                    assetTypeId: "", assetTypeName: "Machinery",         manufacturer: "Ace Micromatic",    modelNo: "LT-28",          serialNo: "ACE20220901A1",   installationDate: "2022-09-01", warrantyDetails: "3 years expires Sep 2025",  level: "1", status: "Active",            consumedHours: "3640",  createdAt: A, updatedAt: A, createdBy: "Admin", updatedBy: "Admin", changelog: C(A) },
  { id: "ast008", assetId: "AST-008", name: "MIG Welding Machine 350A",       locationId: "loc001", locationName: "Production Floor Block A",       assetTypeId: "", assetTypeName: "Welding",           manufacturer: "ESAB India",        modelNo: "Warrior 350i",   serialNo: "ESAB2020060201", installationDate: "2020-06-02", warrantyDetails: "2 years expired Jun 2022",  level: "1", status: "Active",            consumedHours: "8910",  createdAt: A, updatedAt: A, createdBy: "Admin", updatedBy: "Admin", changelog: C(A) },
  { id: "ast009", assetId: "AST-009", name: "Fork Lift 3T Diesel",            locationId: "loc005", locationName: "Warehouse & Dispatch Bay",        assetTypeId: "", assetTypeName: "Material Handling", manufacturer: "Godrej & Boyce",   modelNo: "GX-30",          serialNo: "GDJ210301FL1",    installationDate: "2021-03-01", warrantyDetails: "2 years expired Mar 2023",  level: "1", status: "Active",            consumedHours: "7200",  createdAt: A, updatedAt: A, createdBy: "Admin", updatedBy: "Admin", changelog: C(A) },
  { id: "ast010", assetId: "AST-010", name: "Industrial Chiller 20TR",        locationId: "loc001", locationName: "Production Floor Block A",       assetTypeId: "", assetTypeName: "HVAC & Cooling",    manufacturer: "Blue Star Ltd",     modelNo: "PLCI20TR",       serialNo: "BSL2023070101",   installationDate: "2023-07-01", warrantyDetails: "3 years expires Jul 2026",  level: "1", status: "Active",            consumedHours: "4380",  createdAt: A, updatedAt: A, createdBy: "Admin", updatedBy: "Admin", changelog: C(A) },
  { id: "ast011", assetId: "AST-011", name: "Spot Welder 40kVA",              locationId: "loc002", locationName: "Assembly Bay",                    assetTypeId: "", assetTypeName: "Welding",           manufacturer: "Weldman",           modelNo: "SW-40K",         serialNo: "WLM2019050901",   installationDate: "2019-05-09", warrantyDetails: "2 years expired May 2021",  level: "1", status: "Active",            consumedHours: "14200", createdAt: A, updatedAt: A, createdBy: "Admin", updatedBy: "Admin", changelog: C(A) },
  { id: "ast012", assetId: "AST-012", name: "CMM Zeiss Contura G2",           locationId: "loc006", locationName: "Quality & Testing Lab",           assetTypeId: "", assetTypeName: "Metrology",         manufacturer: "Carl Zeiss India",  modelNo: "Contura G2",     serialNo: "CZ20230201QA1",   installationDate: "2023-02-01", warrantyDetails: "5 years expires Feb 2028",  level: "1", status: "Active",            consumedHours: "2100",  createdAt: A, updatedAt: A, createdBy: "Admin", updatedBy: "Admin", changelog: C(A) },
  { id: "ast013", assetId: "AST-013", name: "Shot Blasting Machine",          locationId: "loc010", locationName: "Paint Shop & Surface Treatment",  assetTypeId: "", assetTypeName: "Surface Treatment", manufacturer: "Wheelabrator India",modelNo: "SB-600",         serialNo: "WBI2017091001",   installationDate: "2017-09-10", warrantyDetails: "2 years expired Sep 2019",  level: "1", status: "Active",            consumedHours: "28400", createdAt: A, updatedAt: A, createdBy: "Admin", updatedBy: "Admin", changelog: C(A) },
  { id: "ast014", assetId: "AST-014", name: "Plasma Cutter 200A",             locationId: "loc001", locationName: "Production Floor Block A",       assetTypeId: "", assetTypeName: "Cutting",           manufacturer: "Hypertherm",        modelNo: "Powermax 200",   serialNo: "HT2022031401",    installationDate: "2022-03-14", warrantyDetails: "3 years expires Mar 2025",  level: "1", status: "Active",            consumedHours: "5600",  createdAt: A, updatedAt: A, createdBy: "Admin", updatedBy: "Admin", changelog: C(A) },
  { id: "ast015", assetId: "AST-015", name: "Industrial Parts Washer",        locationId: "loc009", locationName: "Machine Shop",                    assetTypeId: "", assetTypeName: "Cleaning",          manufacturer: "Teknox",            modelNo: "TWK-400",        serialNo: "TNX2020120501",   installationDate: "2020-12-05", warrantyDetails: "2 years expired Dec 2022",  level: "1", status: "Scrapped",          consumedHours: "9800",  createdAt: A, updatedAt: A, createdBy: "Admin", updatedBy: "Admin", changelog: C(A) },
];

// ─── Maintenance Types ────────────────────────────────────────
const M = "2024-01-08T09:00:00.000Z";
export const SEED_MAINTENANCE_TYPES = [
  { id: "mt001", typeId: "MT-00001", maintenanceName: "Preventive Maintenance",  priority: "Medium",   duration: "4",  isDeactivated: false, createdAt: M, updatedAt: M, createdBy: "Admin", updatedBy: "Admin", changelog: C(M) },
  { id: "mt002", typeId: "MT-00002", maintenanceName: "Breakdown Maintenance",   priority: "Critical", duration: "8",  isDeactivated: false, createdAt: M, updatedAt: M, createdBy: "Admin", updatedBy: "Admin", changelog: C(M) },
  { id: "mt003", typeId: "MT-00003", maintenanceName: "Corrective Maintenance",  priority: "High",     duration: "6",  isDeactivated: false, createdAt: M, updatedAt: M, createdBy: "Admin", updatedBy: "Admin", changelog: C(M) },
  { id: "mt004", typeId: "MT-00004", maintenanceName: "Predictive Maintenance",  priority: "Low",      duration: "2",  isDeactivated: false, createdAt: M, updatedAt: M, createdBy: "Admin", updatedBy: "Admin", changelog: C(M) },
  { id: "mt005", typeId: "MT-00005", maintenanceName: "Overhauling",             priority: "High",     duration: "24", isDeactivated: false, createdAt: M, updatedAt: M, createdBy: "Admin", updatedBy: "Admin", changelog: C(M) },
  { id: "mt006", typeId: "MT-00006", maintenanceName: "Lubrication & Greasing",  priority: "Low",      duration: "1",  isDeactivated: false, createdAt: M, updatedAt: M, createdBy: "Admin", updatedBy: "Admin", changelog: C(M) },
  { id: "mt007", typeId: "MT-00007", maintenanceName: "Calibration",             priority: "Medium",   duration: "3",  isDeactivated: false, createdAt: M, updatedAt: M, createdBy: "Admin", updatedBy: "Admin", changelog: C(M) },
  { id: "mt008", typeId: "MT-00008", maintenanceName: "Inspection & Testing",    priority: "Medium",   duration: "2",  isDeactivated: false, createdAt: M, updatedAt: M, createdBy: "Admin", updatedBy: "Admin", changelog: C(M) },
];

// ─── Job List ─────────────────────────────────────────────────
export const SEED_JOB_LIST = [
  { id: "job001", jobId: "JOB-000001", jobDate: "2026-06-01", assetId: "ast002", assetName: "Air Compressor 150 CFM",  assetLocation: "Compressor House",                maintenanceTypeId: "mt001", maintenanceTypeName: "Preventive Maintenance", priority: "Medium",   problemDescription: "Monthly PM due — check oil level, clean filters, inspect belts and safety valves.",                                     assignedToId: "emp012", assignedToName: "Dinesh Raut",   startTime: "2026-06-01T08:00", endTime: "2026-06-01T12:00", estimatedDuration: "4",  status: "Completed",    actualDuration: "3.5", workDoneRemarks: "Oil changed, air filter cleaned, belt tension adjusted. All safety valves operational. Next PM due 01-Jul-2026.",                consumedHoursUpdate: "12453", attachments: [], createdAt: "2026-06-01T07:30:00.000Z", updatedAt: "2026-06-01T12:15:00.000Z", createdBy: "Admin",        updatedBy: "Dinesh Raut",  changelog: C("2026-06-01T07:30:00.000Z") },
  { id: "job002", jobId: "JOB-000002", jobDate: "2026-06-05", assetId: "ast005", assetName: "Hydraulic Press 100T",    assetLocation: "Production Floor Block A",        maintenanceTypeId: "mt002", maintenanceTypeName: "Breakdown Maintenance",  priority: "Critical", problemDescription: "Press not building pressure beyond 60T. Production halted. Suspected hydraulic pump failure.",                           assignedToId: "emp007", assignedToName: "Suresh Yadav",  startTime: "2026-06-05T09:00", endTime: "2026-06-05T18:00", estimatedDuration: "8",  status: "Completed",    actualDuration: "9",   workDoneRemarks: "Hydraulic pump seal replaced. New seal kit HP-SK-100 installed. System tested at 110T — OK. Asset Under Maintenance pending QC sign-off.", consumedHoursUpdate: "22309", attachments: [], createdAt: "2026-06-05T08:45:00.000Z", updatedAt: "2026-06-05T18:10:00.000Z", createdBy: "Admin",        updatedBy: "Suresh Yadav", changelog: C("2026-06-05T08:45:00.000Z") },
  { id: "job003", jobId: "JOB-000003", jobDate: "2026-06-10", assetId: "ast001", assetName: "CNC Machining Centre",    assetLocation: "Production Floor Block A",        maintenanceTypeId: "mt006", maintenanceTypeName: "Lubrication & Greasing", priority: "Low",      problemDescription: "Scheduled weekly lubrication of spindle ball screws and linear guides.",                                                  assignedToId: "emp012", assignedToName: "Dinesh Raut",   startTime: "2026-06-10T07:30", endTime: "2026-06-10T08:30", estimatedDuration: "1",  status: "Completed",    actualDuration: "1",   workDoneRemarks: "Spindle oil topped up. Ball screws greased with OKS 425. All guide ways lubricated. Machine ready for production.",              consumedHoursUpdate: "4821", attachments: [], createdAt: "2026-06-10T07:00:00.000Z", updatedAt: "2026-06-10T08:45:00.000Z", createdBy: "Admin",        updatedBy: "Dinesh Raut",  changelog: C("2026-06-10T07:00:00.000Z") },
  { id: "job004", jobId: "JOB-000004", jobDate: "2026-06-15", assetId: "ast003", assetName: "DG Set 250 kVA",          assetLocation: "Utility & Services Room",         maintenanceTypeId: "mt001", maintenanceTypeName: "Preventive Maintenance", priority: "Medium",   problemDescription: "Quarterly PM — engine service, coolant check, battery test and full load test.",                                          assignedToId: "emp012", assignedToName: "Dinesh Raut",   startTime: "2026-06-15T09:00", endTime: "2026-06-15T13:30", estimatedDuration: "4",  status: "Completed",    actualDuration: "4.5", workDoneRemarks: "Engine oil & filter changed. Coolant topped. Battery terminals cleaned. Load test at 70% — 415V stable. Next PM: 15-Sep-2026.",    consumedHoursUpdate: "3204", attachments: [], createdAt: "2026-06-15T08:30:00.000Z", updatedAt: "2026-06-15T13:45:00.000Z", createdBy: "Admin",        updatedBy: "Dinesh Raut",  changelog: C("2026-06-15T08:30:00.000Z") },
  { id: "job005", jobId: "JOB-000005", jobDate: "2026-06-20", assetId: "ast004", assetName: "Conveyor Belt System",    assetLocation: "Assembly Bay",                    maintenanceTypeId: "mt003", maintenanceTypeName: "Corrective Maintenance", priority: "High",     problemDescription: "Belt slipping on drive pulley section 3. Tension lost, visible misalignment and abnormal noise on startup.",               assignedToId: "emp007", assignedToName: "Suresh Yadav",  startTime: "2026-06-20T10:00", endTime: "2026-06-20T16:00",  estimatedDuration: "6",  status: "Completed",    actualDuration: "6",   workDoneRemarks: "Drive pulley lagging replaced. Belt re-tensioned and re-aligned per OEM spec. Test run 30 min — no slip. Normal operation resumed.", consumedHoursUpdate: "18601", attachments: [], createdAt: "2026-06-20T09:30:00.000Z", updatedAt: "2026-06-20T16:15:00.000Z", createdBy: "Admin",        updatedBy: "Suresh Yadav", changelog: C("2026-06-20T09:30:00.000Z") },
  { id: "job006", jobId: "JOB-000006", jobDate: "2026-06-22", assetId: "ast006", assetName: "EOT Overhead Crane 5T",   assetLocation: "Assembly Bay",                    maintenanceTypeId: "mt004", maintenanceTypeName: "Predictive Maintenance", priority: "Low",      problemDescription: "Vibration sensor reading elevated on hoist motor. Scheduled inspection before next heavy lift operation.",                  assignedToId: "emp012", assignedToName: "Dinesh Raut",   startTime: "2026-06-22T14:00", endTime: "2026-06-22T16:00", estimatedDuration: "2",  status: "Completed",    actualDuration: "2",   workDoneRemarks: "Hoist motor bearing inspected — slight wear detected. Bearing replaced (SKF 6205ZZ). Vibration levels normal after replacement.", consumedHoursUpdate: "1871", attachments: [], createdAt: "2026-06-22T13:30:00.000Z", updatedAt: "2026-06-22T16:10:00.000Z", createdBy: "Admin",        updatedBy: "Dinesh Raut",  changelog: C("2026-06-22T13:30:00.000Z") },
  { id: "job007", jobId: "JOB-000007", jobDate: "2026-06-25", assetId: "ast001", assetName: "CNC Machining Centre",    assetLocation: "Production Floor Block A",        maintenanceTypeId: "mt003", maintenanceTypeName: "Corrective Maintenance", priority: "High",     problemDescription: "Spindle alarm triggered — Z-axis position error. Machine auto-stopped mid-cycle. Possible tool crash during last op.",    assignedToId: "emp012", assignedToName: "Dinesh Raut",   startTime: "2026-06-25T08:00", endTime: "",                 estimatedDuration: "6",  status: "In Progress",  actualDuration: "",    workDoneRemarks: "",                                                                                                                               consumedHoursUpdate: "", attachments: [], createdAt: "2026-06-25T07:45:00.000Z", updatedAt: "2026-06-25T07:45:00.000Z", createdBy: "Admin",        updatedBy: "Admin",        changelog: C("2026-06-25T07:45:00.000Z") },
  { id: "job008", jobId: "JOB-000008", jobDate: "2026-06-26", assetId: "ast002", assetName: "Air Compressor 150 CFM",  assetLocation: "Compressor House",                maintenanceTypeId: "mt005", maintenanceTypeName: "Overhauling",            priority: "High",     problemDescription: "Annual overhaul due at 12000+ hours. Piston rings, cylinder valves and shaft seals to be replaced per OEM schedule.",    assignedToId: "emp007", assignedToName: "Suresh Yadav",  startTime: "2026-06-26T08:00", endTime: "",                 estimatedDuration: "24", status: "Open",         actualDuration: "",    workDoneRemarks: "",                                                                                                                               consumedHoursUpdate: "", attachments: [], createdAt: "2026-06-26T07:30:00.000Z", updatedAt: "2026-06-26T07:30:00.000Z", createdBy: "Admin",        updatedBy: "Admin",        changelog: C("2026-06-26T07:30:00.000Z") },
  { id: "job009", jobId: "JOB-000009", jobDate: "2026-06-27", assetId: "ast007", assetName: "CNC Lathe LT-28",         assetLocation: "Machine Shop",                    maintenanceTypeId: "mt001", maintenanceTypeName: "Preventive Maintenance", priority: "Medium",   problemDescription: "500-hour scheduled PM — inspect chuck, clean coolant tank, check tailstock alignment, lubricate all slides.",             assignedToId: "emp012", assignedToName: "Dinesh Raut",   startTime: "2026-06-27T09:00", endTime: "",                 estimatedDuration: "4",  status: "Open",         actualDuration: "",    workDoneRemarks: "",                                                                                                                               consumedHoursUpdate: "", attachments: [], createdAt: "2026-06-27T08:30:00.000Z", updatedAt: "2026-06-27T08:30:00.000Z", createdBy: "Admin",        updatedBy: "Admin",        changelog: C("2026-06-27T08:30:00.000Z") },
  { id: "job010", jobId: "JOB-000010", jobDate: "2026-06-12", assetId: "ast008", assetName: "MIG Welding Machine 350A",assetLocation: "Production Floor Block A",        maintenanceTypeId: "mt003", maintenanceTypeName: "Corrective Maintenance", priority: "High",     problemDescription: "Intermittent arc failure during operation. Suspected contact tip wear and gun liner blockage.",                            assignedToId: "emp012", assignedToName: "Dinesh Raut",   startTime: "2026-06-12T13:00", endTime: "2026-06-12T15:00", estimatedDuration: "2",  status: "Completed",    actualDuration: "1.5", workDoneRemarks: "Contact tip replaced (0.8mm). Gun liner cleaned and re-lubricated. Arc stability confirmed. Wire feed tested OK at all speeds.", consumedHoursUpdate: "8911", attachments: [], createdAt: "2026-06-12T12:30:00.000Z", updatedAt: "2026-06-12T15:10:00.000Z", createdBy: "Admin",        updatedBy: "Dinesh Raut",  changelog: C("2026-06-12T12:30:00.000Z") },
  { id: "job011", jobId: "JOB-000011", jobDate: "2026-06-08", assetId: "ast009", assetName: "Fork Lift 3T Diesel",     assetLocation: "Warehouse & Dispatch Bay",        maintenanceTypeId: "mt001", maintenanceTypeName: "Preventive Maintenance", priority: "Medium",   problemDescription: "Monthly PM — engine oil service, hydraulic oil check, tyre inspection, fork crack inspection and brake test.",            assignedToId: "emp007", assignedToName: "Suresh Yadav",  startTime: "2026-06-08T07:30", endTime: "2026-06-08T10:30", estimatedDuration: "3",  status: "Completed",    actualDuration: "3",   workDoneRemarks: "Engine oil and filter replaced. Hydraulic oil level OK. Tyres at correct pressure. No cracks on forks. Brakes tested — OK. Ready for service.", consumedHoursUpdate: "7201", attachments: [], createdAt: "2026-06-08T07:00:00.000Z", updatedAt: "2026-06-08T10:45:00.000Z", createdBy: "Admin", updatedBy: "Suresh Yadav", changelog: C("2026-06-08T07:00:00.000Z") },
  { id: "job012", jobId: "JOB-000012", jobDate: "2026-06-17", assetId: "ast012", assetName: "CMM Zeiss Contura G2",    assetLocation: "Quality & Testing Lab",           maintenanceTypeId: "mt007", maintenanceTypeName: "Calibration",            priority: "Medium",   problemDescription: "Bi-annual calibration due as per ISO 17025 requirement. Probing system and temperature compensation to be verified.",   assignedToId: "emp004", assignedToName: "Priya Desai",   startTime: "2026-06-17T09:00", endTime: "2026-06-17T12:00", estimatedDuration: "3",  status: "Completed",    actualDuration: "3",   workDoneRemarks: "CMM calibrated by certified technician from Zeiss. Calibration certificate No. ZSS-2026-0617. Valid until Dec 2026. All axes within spec.", consumedHoursUpdate: "2101", attachments: [], createdAt: "2026-06-17T08:30:00.000Z", updatedAt: "2026-06-17T12:30:00.000Z", createdBy: "Admin", updatedBy: "Priya Desai", changelog: C("2026-06-17T08:30:00.000Z") },
  { id: "job013", jobId: "JOB-000013", jobDate: "2026-06-03", assetId: "ast013", assetName: "Shot Blasting Machine",   assetLocation: "Paint Shop & Surface Treatment", maintenanceTypeId: "mt006", maintenanceTypeName: "Lubrication & Greasing", priority: "Low",      problemDescription: "Weekly greasing of blast wheel bearings, elevator chain and screw conveyor as per maintenance schedule.",               assignedToId: "emp012", assignedToName: "Dinesh Raut",   startTime: "2026-06-03T07:00", endTime: "2026-06-03T08:00", estimatedDuration: "1",  status: "Completed",    actualDuration: "1",   workDoneRemarks: "All blast wheel bearings greased with SKF LGEP 2. Elevator chain lubricated. Screw conveyor bearings greased. OK.",      consumedHoursUpdate: "28401", attachments: [], createdAt: "2026-06-03T06:45:00.000Z", updatedAt: "2026-06-03T08:05:00.000Z", createdBy: "Admin", updatedBy: "Dinesh Raut", changelog: C("2026-06-03T06:45:00.000Z") },
  { id: "job014", jobId: "JOB-000014", jobDate: "2026-06-24", assetId: "ast010", assetName: "Industrial Chiller 20TR", assetLocation: "Production Floor Block A",        maintenanceTypeId: "mt008", maintenanceTypeName: "Inspection & Testing",   priority: "Medium",   problemDescription: "Chiller outlet temperature rising above setpoint (12°C). Possible refrigerant leak or condenser fouling.",              assignedToId: "emp007", assignedToName: "Suresh Yadav",  startTime: "2026-06-24T11:00", endTime: "",                 estimatedDuration: "2",  status: "In Progress",  actualDuration: "",    workDoneRemarks: "",                                                                                                                               consumedHoursUpdate: "", attachments: [], createdAt: "2026-06-24T10:30:00.000Z", updatedAt: "2026-06-24T11:05:00.000Z", createdBy: "Admin", updatedBy: "Suresh Yadav", changelog: C("2026-06-24T10:30:00.000Z") },
  { id: "job015", jobId: "JOB-000015", jobDate: "2026-06-14", assetId: "ast014", assetName: "Plasma Cutter 200A",      assetLocation: "Production Floor Block A",        maintenanceTypeId: "mt001", maintenanceTypeName: "Preventive Maintenance", priority: "Medium",   problemDescription: "250-hour PM — inspect consumables (nozzle, shield, electrode), clean torch body, check gas flow and coolant level.",    assignedToId: "emp012", assignedToName: "Dinesh Raut",   startTime: "2026-06-14T08:00", endTime: "2026-06-14T10:00", estimatedDuration: "2",  status: "Completed",    actualDuration: "2",   workDoneRemarks: "Nozzle, shield and electrode replaced (Hypertherm OEM parts). Gas flow verified at 70PSI. Coolant level OK. Cut quality test passed.", consumedHoursUpdate: "5601", attachments: [], createdAt: "2026-06-14T07:30:00.000Z", updatedAt: "2026-06-14T10:10:00.000Z", createdBy: "Admin", updatedBy: "Dinesh Raut", changelog: C("2026-06-14T07:30:00.000Z") },
];
